# -*- coding: utf-8 -*-
"""
泛德意志的欧洲 · 历史设定集知识工程 —— 补全数据层
=====================================================
本文件承载「一致性检查与补全」任务新增的内容，由 tools/build.py 合并进主数据层。

内容包括：
  A. 伊比利亚线补全（西班牙-阿拉贡 / 奥克王国 → 伊比利亚王国 → 大革命）
  B. 伊斯兰世界线补全（科尔多瓦、穆瓦希德、法蒂玛、阿尤布、马穆鲁克、
     阿拔斯、波斯、安纳托利亚突厥、阿拉伯、叙利亚、埃及、马格里布）
  C. 未具名人物补全 + 新增人物（含法兰克名人的德语化姓名）
  D. 相关事件、战争、关系、行政区划

命名原则（用户本轮要求：姓名须符合世界线的语言与文化）：
  - 法兰克（西部日耳曼）人物一律用德语名：如 Karl der Große、Ludwig der Heilige、
    Philipp IV.、Johanna von Arkon、Kardinal Richelieu → Reichsleiter Richelieu。
  - 罗曼语族地区（伊比利亚、奥克、不列颠）人物用各自语言的德语化拼写。
  - 伊斯兰世界人物用阿拉伯语/波斯语/突厥语音译（德语学界通行的转写形式）。
  - 所有新增人物凡属推定者，均在 notes 中明确标注「本轮新增（推定）」。
"""

# ============================================================
# A + B. 新增国家 / 政治实体
# ============================================================
COUNTRIES = [
    {
        "id": "C_OCCITAN_KINGDOM", "name_zh": "奥克王国", "name_short": "奥克王国",
        "name_de": "Königreich Okzitanien", "name_local": "Reialme d'Occitània",
        "name_en": "Kingdom of Occitania", "name_en_short": "Occitania",
        "polity": "奥克语地区的独立王国（具体政体文档未载）",
        "polity_en": "Independent kingdom of the Occitan-speaking lands",
        "dynasty": None, "dynasty_id": None,
        "religion": "天主教", "religion_id": "R_CATHOLIC",
        "capital": None, "capital_id": None,
        "capital_note": "文档未指定首都；图卢兹、马西利恩为奥克核心城市",
        "territory": "奥克语地区（朗格多克、普罗旺斯、多菲内、奥克海岸、罗讷河口一带）",
        "territory_axis": "南欧/西地中海；后成为法兰克与伊比利亚之间的争夺地带",
        "language": "伊比利亚-奥克语", "language_id": "L_OCCITAN",
        "peoples": ["奥克人"],
        "founded": "文档未载具体年份",
        "time_span": "— 1648年前后（部分领土被伊比利亚取得）；1789年大革命后其地成为革命军的占领区",
        "overview": "用户本轮补充设定的实体：伊比利亚的前身之一。奥克语地区的政治体，与西班牙-阿拉贡同为伊比利亚统一进程的源头。1648年《维也纳和约》后法兰克在奥克地区占领后撤，伊比利亚获得部分奥克领土；1789年伊比利亚-奥克大革命即爆发于此地区。二战后法兰克获取奥克地区并设南部奥克省。",
        "key_traits": ["伊比利亚的前身之一", "与法兰克长期纠缠", "奥克语与伊比利亚半岛语言共享词汇语法", "奥克人认同“北伊比利亚人”或“奥克-伊比利亚人”"],
        "religions_detail": "天主教",
        "allies": ["C_IBERIAN_KINGDOM", "C_SPAIN_ARAGON"],
        "enemies": ["C_FRANKEN"],
        "wars": ["W_RELIGION", "W_REV_IBERIA", "W_RECONQUISTA"],
        "treaties": ["T_VIENNA_1648"],
        "policies": [],
        "subdivisions": [], "parties": [], "orgs": [],
        "status": "已确定", "src": ["S0", "S1", "S2"],
        "notes": "S0/S1 未使用“奥克王国”这一国号，仅在《设定集补充2》的伊比利亚早期方案中出现过“奥克王国”一词。用户本轮明确将其列为伊比利亚的前身之一，故正式立为国实体。政体、王朝、世系均待定。",
    },
    {
        "id": "C_ISLAMIC_WORLD", "name_zh": "伊斯兰世界（区域文明体集合）", "name_short": "伊斯兰世界",
        "name_de": "Islamische Welt", "name_local": "العالم الإسلامي",
        "name_en": "The Islamic World", "name_en_short": "Islamdom",
        "polity": "哈里发—苏丹—沙阿多中心体系；无单一最高政治权威",
        "polity_en": "Multi-centred caliphate-sultanate-shahdom system",
        "dynasty": None, "dynasty_id": None,
        "religion": "伊斯兰教（逊尼派、什叶派并存）", "religion_id": "R_ISLAM",
        "capital": None, "capital_id": None,
        "capital_note": "无单一首都：科尔多瓦、开罗、大马士革、巴格达、伊斯法罕、君士坦丁堡先后为区域中心",
        "territory": "伊比利亚南部（至收复失地运动）、北非、埃及、叙利亚、阿拉伯半岛、两河、伊朗、安纳托利亚、中亚西部",
        "territory_axis": "亚洲西部与中部；撒哈拉以北非洲东部划入亚洲",
        "language": "阿拉伯语、波斯语、突厥语", "language_id": None,
        "peoples": ["阿拉伯人", "波斯人", "突厥人", "柏柏尔人", "马穆鲁克", "库尔德人"],
        "founded": "7世纪",
        "time_span": "7世纪 — 至今",
        "overview": "本世界线的区域文明体集合。S1 明确本世界并非“消灭伊斯兰世界”，而是重新划定伊斯兰文明的东部边界：伊斯兰化止步于更西侧，西域/塔里木保持佛教。其西线则在伊比利亚被逐出，但北非西部到19—20世纪仍为伊比利亚国家的一部分。西亚（阿拉伯—伊朗—两河—安纳托利亚）仍以伊斯兰文明为主。",
        "key_traits": ["多中心、无单一最高权威", "逊尼派与什叶派二分", "西线止于伊比利亚—马格里布，东线止于河中", "埃及/叙利亚/阿拉伯/安纳托利亚/波斯各自形成独立政治传统"],
        "religions_detail": "西亚仍以伊斯兰文明为主（阿拉伯—伊朗—两河—安纳托利亚）；中亚西部仍有较强伊斯兰影响；河中地区穆斯林影响强",
        "allies": [], "enemies": [],
        "wars": ["W_RECONQUISTA", "W_CRUSADES"],
        "treaties": [], "policies": [],
        "subdivisions": [], "parties": [], "orgs": [],
        "status": "已确定", "src": ["S1", "S2"],
        "notes": "S1 明定“削弱伊斯兰教在亚洲中部、东部的长期统治范围，但不是消灭伊斯兰世界”。本条目为集合性区域实体；下辖各哈里发国/苏丹国单列。",
    },
    {
        "id": "C_IBERIAN_KINGDOM", "name_zh": "伊比利亚王国", "name_short": "伊比利亚王国",
        "name_de": "Königreich Iberien", "name_local": "Reino de Iberia",
        "name_en": "Kingdom of Iberia", "name_en_short": "Iberia",
        "polity": "中央集权君主国（统一伊比利亚半岛与北非西部）",
        "polity_en": "Centralised monarchy ruling the Iberian peninsula and western North Africa",
        "dynasty": "伊比利亚王朝（由西班牙-阿拉贡与奥克王国的王朝合并而成，具体王朝名待定）",
        "dynasty_id": "D_IBERIA_DYNASTY",
        "religion": "天主教", "religion_id": "R_CATHOLIC",
        "capital": "托莱多（推定）", "capital_id": "P_TOLEDO",
        "capital_note": "文档未指定首都；托莱多为推定，另见待定项",
        "territory": "伊比利亚半岛全境（卡斯蒂利亚、阿拉贡、葡萄牙、纳瓦拉、格拉纳达）与北非西部（马格里布）",
        "territory_axis": "西南欧 + 西马格里布；文明地理上属欧洲",
        "language": "伊比利亚-奥克语", "language_id": "L_OCCITAN",
        "peoples": ["伊比利亚人", "奥克人", "马格里布基督教化居民"],
        "founded": "伊比利亚各基督教王国完成统一、并南下北非驱逐穆斯林后建立（具体年份待定）",
        "time_span": "— 1789（伊比利亚-奥克大革命中推翻）",
        "overview": "用户本轮补充设定的实体。由西班牙-阿拉贡（及奥克王国）为起点，逐步统一伊比利亚各基督教王国，并南下北非驱逐穆斯林，最终建立伊比利亚王国。该王国在1789年伊比利亚-奥克大革命中被推翻，此后进入共和国/帝国反复更替的时代。",
        "key_traits": ["统一伊比利亚半岛", "南下北非驱逐穆斯林", "中央集权从未真正逆转", "在1789年大革命中被推翻"],
        "religions_detail": "天主教；以宗教统一为立国原则之一，长期压制国内新教徒与残余穆斯林",
        "allies": ["C_OCCITAN_KINGDOM"],
        "enemies": ["C_FRANKEN", "C_ALMOHAD"],
        "wars": ["W_RECONQUISTA"],
        "treaties": ["T_VIENNA_1648"],
        "policies": ["驱逐穆斯林", "同化边缘民族，不建民族邦"],
        "subdivisions": [], "parties": [], "orgs": [],
        "status": "已确定", "src": ["S0", "S2"],
        "notes": "本轮新增（用户补充）。S0/S2 只记“伊比利亚王国→第一共和国→第一帝国……”，未记其如何形成；本轮补齐为“西班牙-阿拉贡（及奥克王国）→逐步统一＋南下北非→伊比利亚王国→1789被推翻”。王朝名与建国的确切年份仍待定。",
    },
    {
        "id": "C_CORDOBA", "name_zh": "科尔多瓦哈里发国", "name_short": "科尔多瓦",
        "name_de": "Kalifat von Córdoba", "name_local": "خلافة قرطبة",
        "name_en": "Caliphate of Córdoba", "name_en_short": "Córdoba",
        "polity": "哈里发国（929年自立哈里发）",
        "polity_en": "Caliphate (self-proclaimed 929)",
        "dynasty": "伍麦叶（西班牙支系）", "dynasty_id": "D_UMAYYAD",
        "religion": "伊斯兰教（逊尼派）", "religion_id": "R_ISLAM",
        "capital": "科尔多瓦", "capital_id": "P_CORDOBA", "capital_note": None,
        "territory": "伊比利亚半岛大部（安达卢斯）",
        "territory_axis": "伊比利亚南部；1031年后分裂为诸泰法",
        "language": "阿拉伯语", "language_id": None,
        "peoples": ["阿拉伯人", "柏柏尔人", "穆拉迪", "莫扎拉布"],
        "founded": "929（阿卜杜勒·拉赫曼三世自立哈里发）",
        "time_span": "929 — 1031（分裂为诸泰法）",
        "overview": "伊比利亚的穆斯林政权，8世纪起统治半岛大部，929年自立哈里发。1031年分裂为诸多泰法小国，为北方基督教诸王国的推进提供条件。此后由北非的穆拉比特与穆瓦希德两王朝先后渡海接管安达卢斯。",
        "key_traits": ["安达卢斯文明中心", "1031年后分裂为泰法诸国", "后被北非柏柏尔王朝接管"],
        "religions_detail": "伊斯兰教逊尼派",
        "allies": ["C_ALMOHAD"], "enemies": ["C_IBERIAN_KINGDOM", "C_SPAIN_ARAGON"],
        "wars": ["W_RECONQUISTA"], "treaties": [], "policies": [],
        "subdivisions": [], "parties": [], "orgs": [],
        "status": "已确定", "src": ["S0", "S2"],
        "notes": "本轮新增（推定补全）。S2 第十八节的伊比利亚历史链条以“收复失地运动”为起点，其政治对位方即安达卢斯的穆斯林政权；S1 明列“安纳托利亚：伊斯兰与基督教并存/竞争”“阿拉伯：伊斯兰”。",
    },
    {
        "id": "C_ALMOHAD", "name_zh": "穆瓦希德哈里发国（及穆拉比特）", "name_short": "穆瓦希德",
        "name_de": "Almohadenkalifat (und Almoraviden)", "name_local": "الموحدون",
        "name_en": "Almohad Caliphate (and Almoravids)", "name_en_short": "Almohads",
        "polity": "柏柏尔哈里发国（北非—安达卢斯联合体）",
        "polity_en": "Berber caliphate uniting the Maghreb and al-Andalus",
        "dynasty": "穆拉比特 → 穆瓦希德", "dynasty_id": "D_ALMOHAD",
        "religion": "伊斯兰教（逊尼派，严格派）", "religion_id": "R_ISLAM",
        "capital": "马拉喀什", "capital_id": "P_MARRAKECH", "capital_note": None,
        "territory": "马格里布（今摩洛哥、阿尔及利亚一带）与安达卢斯南部",
        "territory_axis": "西北非—伊比利亚南部",
        "language": "柏柏尔语、阿拉伯语", "language_id": None,
        "peoples": ["柏柏尔人", "阿拉伯人"],
        "founded": "11世纪（穆拉比特）→ 12世纪（穆瓦希德）",
        "time_span": "11世纪 — 13世纪（1212年后在伊比利亚崩溃）",
        "overview": "北非柏柏尔人的两个王朝，先后渡海接管安达卢斯。1212年战败后其在伊比利亚的统治崩溃，伊比利亚各基督教王国由此得以完成收复失地运动并南下北非。",
        "key_traits": ["北非—安达卢斯联合体", "1212年后在伊比利亚崩溃", "伊比利亚南下北非的直接对位方"],
        "religions_detail": "伊斯兰教逊尼派",
        "allies": ["C_CORDOBA"], "enemies": ["C_IBERIAN_KINGDOM", "C_SPAIN_ARAGON"],
        "wars": ["W_RECONQUISTA"], "treaties": [], "policies": [],
        "subdivisions": [], "parties": [], "orgs": [],
        "status": "已确定", "src": ["S0", "S2"],
        "notes": "本轮新增（推定补全）。",
    },
    {
        "id": "C_FATIMID", "name_zh": "法蒂玛哈里发国（埃及）", "name_short": "法蒂玛",
        "name_de": "Fatimidenkalifat", "name_local": "الدولة الفاطمية",
        "name_en": "Fatimid Caliphate", "name_en_short": "Fatimids",
        "polity": "什叶派哈里发国", "polity_en": "Ismaili Shia caliphate",
        "dynasty": "法蒂玛", "dynasty_id": "D_FATIMID",
        "religion": "伊斯兰教（伊斯玛仪派什叶派）", "religion_id": "R_ISLAM",
        "capital": "开罗", "capital_id": "P_CAIRO",
        "capital_note": "969年建开罗，为法蒂玛王朝首都",
        "territory": "埃及、叙利亚南部、阿拉伯半岛西部（汉志）、北非东部",
        "territory_axis": "地中海东岸与北非东部",
        "language": "阿拉伯语", "language_id": None,
        "peoples": ["阿拉伯人", "柏柏尔人", "埃及科普特人"],
        "founded": "909", "time_span": "909 — 1171",
        "overview": "埃及的什叶派哈里发国，以开罗为中心，势力及于叙利亚与汉志。1171年被萨拉丁推翻，埃及转入逊尼派阿尤布王朝。",
        "key_traits": ["什叶派哈里发国", "开罗为都", "与阿拔斯哈里发国对立"],
        "religions_detail": "伊斯玛仪派什叶派",
        "allies": [], "enemies": ["C_ABBASID"],
        "wars": ["W_CRUSADES"], "treaties": [], "policies": [],
        "subdivisions": [], "parties": [], "orgs": [],
        "status": "已确定", "src": ["S1", "S2"],
        "notes": "本轮新增（推定补全）。S1 只列区域文明，未列具体政权；此处按通行史实补齐政体序列。",
    },
    {
        "id": "C_AYYUBID", "name_zh": "阿尤布苏丹国（埃及—叙利亚）", "name_short": "阿尤布",
        "name_de": "Ayyubidensultanat", "name_local": "الدولة الأيوبية",
        "name_en": "Ayyubid Sultanate", "name_en_short": "Ayyubids",
        "polity": "逊尼派苏丹国", "polity_en": "Sunni sultanate",
        "dynasty": "阿尤布", "dynasty_id": "D_AYYUBID",
        "religion": "伊斯兰教（逊尼派）", "religion_id": "R_ISLAM",
        "capital": "开罗", "capital_id": "P_CAIRO",
        "capital_note": "后以大马士革为第二中心",
        "territory": "埃及、叙利亚、巴勒斯坦、汉志、也门",
        "territory_axis": "黎凡特与埃及",
        "language": "阿拉伯语、库尔德语", "language_id": None,
        "peoples": ["阿拉伯人", "库尔德人", "突厥人"],
        "founded": "1171", "time_span": "1171 — 1250（马穆鲁克取而代之）",
        "overview": "萨拉丁建立的逊尼派苏丹国，统合埃及与叙利亚，是十字军东征时期穆斯林一方的主要政治体。1250年被马穆鲁克王朝取代。",
        "key_traits": ["萨拉丁建立", "统合埃及与叙利亚", "十字军的主要对位方"],
        "religions_detail": "伊斯兰教逊尼派",
        "allies": [], "enemies": ["C_FRANKEN", "C_PAPAL", "C_BYZANTIUM"],
        "wars": ["W_CRUSADES"], "treaties": [], "policies": [],
        "subdivisions": [], "parties": [], "orgs": [],
        "status": "已确定", "src": ["S1"],
        "notes": "本轮新增（推定补全）。S1 记法兰克“拥有北非、黎凡特传统影响”，且首都（原文作“巴黎”，本库统一作帕里斯）有东方学传统；其历史对位方即黎凡特的伊斯兰政权。",
    },
    {
        "id": "C_MAMLUK", "name_zh": "马穆鲁克苏丹国（埃及—叙利亚）", "name_short": "马穆鲁克",
        "name_de": "Mamlukensultanat", "name_local": "دولة المماليك",
        "name_en": "Mamluk Sultanate", "name_en_short": "Mamluks",
        "polity": "军事寡头苏丹国（伯海里系 → 布尔吉系）",
        "polity_en": "Military-oligarchic sultanate (Bahri then Burji)",
        "dynasty": "马穆鲁克", "dynasty_id": "D_MAMLUK",
        "religion": "伊斯兰教（逊尼派）", "religion_id": "R_ISLAM",
        "capital": "开罗", "capital_id": "P_CAIRO", "capital_note": None,
        "territory": "埃及、叙利亚、巴勒斯坦、汉志",
        "territory_axis": "黎凡特与埃及",
        "language": "阿拉伯语、突厥语（钦察）", "language_id": None,
        "peoples": ["马穆鲁克（钦察突厥、高加索来源）", "阿拉伯人", "科普特人"],
        "founded": "1250", "time_span": "1250 — 1517（被安纳托利亚突厥帝国取代）",
        "overview": "由军事奴隶精英建立的苏丹国。1260年阻止蒙古西进，此后长期统治埃及与叙利亚，是东地中海与红海贸易的关键政治体。1517年并入安纳托利亚的突厥帝国。",
        "key_traits": ["1260年阻止蒙古西进", "东地中海与红海贸易枢纽", "1517年被突厥帝国取代"],
        "religions_detail": "伊斯兰教逊尼派；哈里发名义上受其庇护",
        "allies": [], "enemies": ["C_MONGOL_EMPIRE", "C_ANATOLIAN_TURKS"],
        "wars": ["W_MONGOL_EXPANSION"], "treaties": [], "policies": [],
        "subdivisions": [], "parties": [], "orgs": [],
        "status": "已确定", "src": ["S1", "S4"],
        "notes": "本轮新增（推定补全）。S4 明定金帐汗国未伊斯兰化、蒙古文明遗产深厚；马穆鲁克作为蒙古西进的实际阻挡者须在设定中存在。",
    },
    {
        "id": "C_ABBASID", "name_zh": "阿拔斯哈里发国（两河）", "name_short": "阿拔斯",
        "name_de": "Abbasidenkalifat", "name_local": "الدولة العباسية",
        "name_en": "Abbasid Caliphate", "name_en_short": "Abbasids",
        "polity": "哈里发国（后期为名义宗主权）",
        "polity_en": "Caliphate (later largely nominal suzerainty)",
        "dynasty": "阿拔斯", "dynasty_id": "D_ABBASID",
        "religion": "伊斯兰教（逊尼派）", "religion_id": "R_ISLAM",
        "capital": "巴格达", "capital_id": "P_BAGHDAD", "capital_note": None,
        "territory": "两河、伊朗、阿拉伯半岛东部；后期仅存两河",
        "territory_axis": "两河与伊朗",
        "language": "阿拉伯语、波斯语", "language_id": None,
        "peoples": ["阿拉伯人", "波斯人", "突厥人"],
        "founded": "750", "time_span": "750 — 1258（巴格达陷落）",
        "overview": "以巴格达为中心的哈里发国，是伊斯兰世界逊尼派名义上的最高权威。1258年巴格达陷落于蒙古西征军，此后哈里发名义由马穆鲁克庇护。",
        "key_traits": ["逊尼派名义最高权威", "1258年巴格达陷落于蒙古", "两河为伊斯兰文明核心区之一"],
        "religions_detail": "伊斯兰教逊尼派",
        "allies": [], "enemies": ["C_FATIMID", "C_MONGOL_EMPIRE"],
        "wars": ["W_MONGOL_EXPANSION"], "treaties": [], "policies": [],
        "subdivisions": [], "parties": [], "orgs": [],
        "status": "已确定", "src": ["S1"],
        "notes": "本轮新增（推定补全）。S1 明列“两河：伊斯兰”为区域主导文明。",
    },
    {
        "id": "C_PERSIA", "name_zh": "伊朗（伊斯兰什叶派波斯）", "name_short": "伊朗",
        "name_de": "Persisches Reich", "name_local": "ایران",
        "name_en": "Persia", "name_en_short": "Persia",
        "polity": "沙阿制；什叶派逐步成为国教",
        "polity_en": "Shahdom with Twelver Shi'ism developing into the state religion",
        "dynasty": "诸波斯王朝（11—16世纪陆续更替，详见 D_PERSIAN_LINE）",
        "dynasty_id": "D_PERSIAN_LINE",
        "religion": "伊斯兰教（伊斯玛仪派 → 十二伊玛目派什叶派为国教）", "religion_id": "R_ISLAM",
        "capital": "伊斯法罕（后期）", "capital_id": "P_ISFAHAN",
        "capital_note": "前期诸王朝分都于内沙布尔、雷伊、大不里士、设拉子等地",
        "territory": "伊朗高原、两河东部、呼罗珊、高加索南部、中亚西部边缘",
        "territory_axis": "亚洲西部—中部之间；伊斯兰文明的东部锚点",
        "language": "波斯语（阿拉伯语为宗教与学术语）", "language_id": None,
        "peoples": ["波斯人", "突厥人", "库尔德人", "卢尔人"],
        "founded": "7世纪阿拉伯征服后逐步形成独立波斯政权；11世纪起由突厥—波斯混合王朝主导",
        "time_span": "7世纪 — 至今",
        "overview": "「波斯」概念在本世界线中被撕裂为两支：一支是伊斯兰化的什叶派波斯，即本条目「伊朗」；另一支是退守河中及以东、保持佛教的「西域-波斯残余」（见 C_PERSIA_BUDDHIST）。波斯曾抵御伊斯兰入侵，后因内乱而退守河中及以东，伊朗遂成为伊斯兰文明东端的什叶派国家，与逊尼派的阿拉伯—安纳托利亚体系长期并立。",
        "key_traits": ["什叶派国家传统（伊斯兰化的波斯）", "波斯语高文化", "与逊尼派阿拉伯—安纳托利亚体系并立", "其东侧紧邻退守河中的佛教-西域波斯残余"],
        "religions_detail": "伊斯玛仪派 → 十二伊玛目派什叶派为国教",
        "allies": [], "enemies": ["C_ANATOLIAN_TURKS", "C_ABBASID", "C_PERSIA_BUDDHIST"],
        "wars": ["W_MONGOL_EXPANSION"], "treaties": [], "policies": [],
        "subdivisions": [], "parties": [], "orgs": [],
        "status": "已确定", "src": ["S1"],
        "notes": "S1 明列“伊朗：伊斯兰”为区域主导文明。用户本轮裁定（P5）：波斯曾抵御伊斯兰入侵，后因内乱退守河中及以东；「波斯」概念撕裂为伊斯兰什叶派波斯（即本条目「伊朗」）与佛教-西域波斯残余。",
    },
    {
        "id": "C_ANATOLIAN_TURKS", "name_zh": "奥斯曼帝国（安纳托利亚突厥帝国）", "name_short": "奥斯曼帝国",
        "name_de": "Osmanisches Reich", "name_local": "Osmanlı İmparatorluğu",
        "name_en": "Anatolian Turkish Empire", "name_en_short": "Anatolian Turks",
        "polity": "苏丹—帝国制；逊尼派伊斯兰国家，行米勒特式多宗教治理",
        "polity_en": "Sultanate-empire; Sunni Islamic state with millet-style multi-confessional governance",
        "dynasty": "安纳托利亚突厥王朝（详见 D_OTTOMAN）", "dynasty_id": "D_OTTOMAN",
        "religion": "伊斯兰教（逊尼派）；境内东正教、亚美尼亚教会等并存", "religion_id": "R_ISLAM",
        "capital": "君士坦丁堡（1517年后）", "capital_id": "P_CONSTANTINOPLE",
        "capital_note": "早期都于布尔萨、埃迪尔内（Bursa / Edirne）",
        "territory": "安纳托利亚、巴尔干南部、叙利亚、埃及、汉志、两河；1517年取代马穆鲁克",
        "territory_axis": "东地中海与近东；与基督教君士坦丁堡/海峡政治体长期并存竞争",
        "language": "突厥语（奥斯曼突厥语）；阿拉伯语、波斯语为文化与宗教语", "language_id": None,
        "peoples": ["突厥人", "阿拉伯人", "库尔德人", "希腊人", "亚美尼亚人", "斯拉夫人"],
        "founded": "13世纪末（安纳托利亚西北部起家）",
        "time_span": "13世纪末 — 至今",
        "overview": "安纳托利亚的突厥穆斯林帝国。本世界线中伊斯兰世界在东部受限于西域佛教带，因此安纳托利亚成为伊斯兰力量向欧洲方向的主要压力来源。S1 明确“安纳托利亚：伊斯兰与基督教并存/竞争”，且“君士坦丁堡：基督教文明核心之一”，故本帝国与海峡基督教政治体长期对峙共处。",
        "key_traits": ["逊尼派伊斯兰帝国", "米勒特式多宗教治理", "1517年取代马穆鲁克", "安纳托利亚为伊斯兰与基督教并存/竞争地带"],
        "religions_detail": "逊尼派伊斯兰为国教；东正教、亚美尼亚教会等作为受保护的宗教共同体存在",
        "allies": [], "enemies": ["C_PERSIA", "C_BYZANTIUM", "C_MAMLUK"],
        "wars": ["W_CRUSADES"], "treaties": [], "policies": [],
        "subdivisions": [], "parties": [], "orgs": [],
        "status": "已确定", "src": ["S1"],
        "notes": "用户本轮裁定（P6）：采用「奥斯曼」（德语 Osmanen）。S1《君士坦丁堡问题》要求“安纳托利亚内部仍然可以形成强大的突厥穆斯林国家”，同时“保留一个具有战略意义的基督教君士坦丁堡/海峡政治体”；“海峡是文明边界，而不是文明墙”。",
    },
    {
        "id": "C_MAGHREB", "name_zh": "马格里布（北非西部）", "name_short": "马格里布",
        "name_de": "Maghreb", "name_local": "المغرب",
        "name_en": "The Maghreb", "name_en_short": "Maghreb",
        "polity": "柏柏尔诸王朝 → 伊比利亚国家行政体系的一部分",
        "polity_en": "Berber dynasties, later part of the Iberian state administration",
        "dynasty": "穆拉比特 → 穆瓦希德 → 后由伊比利亚统治", "dynasty_id": "D_ALMOHAD",
        "religion": "伊斯兰教 → 经伊比利亚长期统治后基督教化", "religion_id": "R_CATHOLIC",
        "capital": None, "capital_id": None,
        "capital_note": "马拉喀什、非斯、突尼斯先后为区域中心",
        "territory": "今摩洛哥、阿尔及利亚、突尼斯、西撒哈拉一带",
        "territory_axis": "西北非；文明地理上：撒哈拉以北西部划入欧洲，以东划入亚洲",
        "language": "柏柏尔语、阿拉伯语 → 伊比利亚-奥克语作为行政语言",
        "language_id": "L_OCCITAN",
        "peoples": ["柏柏尔人", "阿拉伯人", "马格里布基督教化居民"],
        "founded": "7世纪阿拉伯征服后伊斯兰化；11世纪起柏柏尔王朝",
        "time_span": "伊斯兰化（7世纪）→ 柏柏尔诸王朝 → 伊比利亚南下驱逐穆斯林 → 19—20世纪为伊比利亚本土一部分",
        "overview": "北非西部。7世纪起伊斯兰化，11—13世纪由柏柏尔王朝（穆拉比特、穆瓦希德）统治并渡海接管安达卢斯。此后伊比利亚各基督教王国南下驱逐穆斯林，长期统治并基督教化、欧洲化该地区。S2 明确其“没有特殊宪制地位”，与伊比利亚半岛同属一个国家行政体系。",
        "key_traits": ["伊比利亚南下驱逐穆斯林的对象", "长期被基督教化、欧洲化", "无特殊宪制地位，非殖民地", "撒哈拉承担文明分界：以北西部属欧洲、以东属亚洲"],
        "religions_detail": "伊斯兰化后被伊比利亚长期统治而基督教化",
        "allies": [], "enemies": ["C_IBERIAN_KINGDOM"],
        "wars": ["W_RECONQUISTA"], "treaties": [], "policies": [],
        "subdivisions": [], "parties": [], "orgs": [],
        "status": "已确定", "src": ["S0", "S2"],
        "notes": "S0 记伊比利亚“统治北非西部”；S2 第19/20/29节明确北非西部为伊比利亚本土一部分、无特殊宪制地位、文明地理上属欧洲。",
    },
    {
        "id": "C_EGYPT_REGION", "name_zh": "埃及地区", "name_short": "埃及",
        "name_de": "Ägypten", "name_local": "مصر",
        "name_en": "Egypt", "name_en_short": "Egypt",
        "polity": "先后为法蒂玛、阿尤布、马穆鲁克、安纳托利亚突厥帝国属地",
        "polity_en": "Successively Fatimid, Ayyubid, Mamluk and Anatolian Turkish territory",
        "dynasty": None, "dynasty_id": None,
        "religion": "伊斯兰教（逊尼派为主）；科普特教会长期存续", "religion_id": "R_ISLAM",
        "capital": "开罗", "capital_id": "P_CAIRO", "capital_note": None,
        "territory": "尼罗河流域、红海西岸、地中海南岸东部",
        "territory_axis": "北非东部；S2 四大洲划分中“撒哈拉以北非洲东部”划入亚洲",
        "language": "阿拉伯语；科普特语为礼仪语言", "language_id": None,
        "peoples": ["埃及人", "科普特人", "阿拉伯人", "马穆鲁克"],
        "founded": "7世纪阿拉伯征服",
        "time_span": "7世纪 — 至今",
        "overview": "尼罗河流域。法蒂玛王朝在此建开罗；此后历经阿尤布、马穆鲁克，1517年并入安纳托利亚突厥帝国。是东地中海与印度洋贸易的关键中转。按 S2 的大洲划分，埃及属“撒哈拉以北非洲东部”，文明地理上划入亚洲。",
        "key_traits": ["东地中海—印度洋贸易中转", "科普特教会长期存续", "文明地理上属亚洲（撒哈拉以北东部）"],
        "religions_detail": "逊尼派伊斯兰为主；科普特教会长期存续",
        "allies": [], "enemies": [],
        "wars": ["W_CRUSADES"], "treaties": [], "policies": [],
        "subdivisions": [], "parties": [], "orgs": [],
        "status": "已确定", "src": ["S2"],
        "notes": "本轮新增（推定补全）。S2 第29节：亚洲包括“撒哈拉以北非洲东部”，埃及是该分区的核心地区。",
    },
    {
        "id": "C_SYRIA", "name_zh": "叙利亚地区", "name_short": "叙利亚",
        "name_de": "Syrien", "name_local": "سوريا",
        "name_en": "Syria", "name_en_short": "Syria",
        "polity": "先后为法蒂玛、阿尤布、马穆鲁克、安纳托利亚突厥帝国属地",
        "polity_en": "Successively Fatimid, Ayyubid, Mamluk and Anatolian Turkish territory",
        "dynasty": None, "dynasty_id": None,
        "religion": "伊斯兰教（逊尼派、什叶派及诸教派并存）；基督徒与犹太社群长期存在",
        "religion_id": "R_ISLAM",
        "capital": "大马士革", "capital_id": "P_DAMASCUS", "capital_note": None,
        "territory": "黎凡特（叙利亚、巴勒斯坦、黎巴嫩沿海）",
        "territory_axis": "东地中海沿岸；法兰克东方学传统的实际接触面",
        "language": "阿拉伯语、阿拉米语残余", "language_id": None,
        "peoples": ["阿拉伯人", "叙利亚基督徒", "德鲁兹", "阿拉维"],
        "founded": "7世纪",
        "time_span": "7世纪 — 至今",
        "overview": "东地中海沿岸的伊斯兰地区，十字军东征的主要战场。S1 特别指出法兰克“拥有地中海传统……拥有北非、黎凡特传统影响”，且首都（原文作“巴黎”，本库统一作帕里斯）有神学、历史、东方学传统，因此法兰克自然会成为“欧洲研究东方世界的重要文明”——其直接接触面即叙利亚与黎凡特。",
        "key_traits": ["十字军东征主战场", "法兰克东方学传统的接触面", "多教派并存"],
        "religions_detail": "逊尼派为主，什叶派诸支派与基督徒社群并存",
        "allies": [], "enemies": ["C_FRANKEN"],
        "wars": ["W_CRUSADES"], "treaties": [], "policies": [],
        "subdivisions": [], "parties": [], "orgs": [],
        "status": "已确定", "src": ["S1"],
        "notes": "本轮新增（推定补全）。S1 明列“中东：穆斯林西亚”并单列法兰克与近东的关系。",
    },
    {
        "id": "C_ARABIA", "name_zh": "阿拉伯—汉志地区", "name_short": "阿拉伯",
        "name_de": "Arabien und Hedschas", "name_local": "الحجاز",
        "name_en": "Arabia and the Hejaz", "name_en_short": "Arabia",
        "polity": "谢里夫/埃米尔地方政权；名义上隶属区域强权",
        "polity_en": "Sharifian/emiral local polities under nominal regional suzerainty",
        "dynasty": None, "dynasty_id": None,
        "religion": "伊斯兰教（逊尼派为主，麦加、麦地那两圣地所在）", "religion_id": "R_ISLAM",
        "capital": None, "capital_id": None,
        "capital_note": "无统一首都；麦加、麦地那为宗教中心",
        "territory": "阿拉伯半岛、汉志、红海东岸",
        "territory_axis": "阿拉伯半岛；红海—印度洋贸易枢纽",
        "language": "阿拉伯语", "language_id": None,
        "peoples": ["阿拉伯人", "贝都因诸部"],
        "founded": "7世纪",
        "time_span": "7世纪 — 至今",
        "overview": "麦加与麦地那两圣地所在。政治上长期为地方谢里夫政权，名义上隶属先后更替的区域强权（阿拔斯、法蒂玛、马穆鲁克、安纳托利亚突厥帝国）。红海贸易为其经济命脉。",
        "key_traits": ["两圣地所在", "红海—印度洋贸易枢纽", "政治上长期为地方政权"],
        "religions_detail": "逊尼派为主",
        "allies": [], "enemies": [],
        "wars": [], "treaties": [], "policies": [],
        "subdivisions": [], "parties": [], "orgs": [],
        "status": "已确定", "src": ["S1"],
        "notes": "本轮新增（推定补全）。S1 明列“阿拉伯：伊斯兰”为区域主导文明。",
    },
]

# ============================================================
# 王朝 / 家族补全
# ============================================================
DYNASTIES = [
    {
        "id": "D_UMAYYAD", "name_zh": "伍麦叶（西班牙支系）", "name_de": "Umayyaden (spanische Linie)",
        "name_en": "Umayyad (Andalusi branch)", "name_local": "الأمويون",
        "type": "王朝", "polity": ["C_CORDOBA"],
        "origin": "大马士革伍麦叶王朝覆灭后，其支系于756年在伊比利亚自立",
        "founded": "756（伊比利亚支系）/ 929（自立哈里发）",
        "ends": "1031（科尔多瓦哈里发国分裂）",
        "religion": "伊斯兰教（逊尼派）", "religion_id": "R_ISLAM",
        "capital": "科尔多瓦", "capital_id": "P_CORDOBA",
        "key_dates": ["756 伊比利亚支系自立", "929 阿卜杜勒·拉赫曼三世自立哈里发", "1031 分裂为诸泰法"],
        "overview": "伊比利亚的穆斯林统治王朝，使科尔多瓦成为西欧最繁盛的城市之一。其衰落后安达卢斯分裂，为北方基督教王国与北非柏柏尔王朝双向介入提供空间。",
        "holdings": ["伊比利亚半岛大部"],
        "members": ["PE_ABD_AL_RAHMAN_III"],
        "status": "已确定", "src": ["S0", "S2"],
        "notes": "本轮新增（推定补全）。",
    },
    {
        "id": "D_ALMOHAD", "name_zh": "穆瓦希德（及穆拉比特）", "name_de": "Almohaden (und Almoraviden)",
        "name_en": "Almohads (and Almoravids)", "name_local": "الموحدون",
        "type": "王朝", "polity": ["C_ALMOHAD", "C_MAGHREB"],
        "origin": "北非柏柏尔人的宗教—军事运动",
        "founded": "11世纪（穆拉比特）→ 12世纪（穆瓦希德）",
        "ends": "13世纪（1212年后在伊比利亚崩溃）",
        "religion": "伊斯兰教（逊尼派，严格派）", "religion_id": "R_ISLAM",
        "capital": "马拉喀什", "capital_id": "P_MARRAKECH",
        "key_dates": ["11世纪 穆拉比特渡海接管安达卢斯", "12世纪 穆瓦希德取而代之", "1212 战败，伊比利亚统治崩溃"],
        "overview": "北非—安达卢斯联合体的两个柏柏尔王朝。其1212年的战败是伊比利亚收复失地运动的转折点，也是伊比利亚得以南下北非的前提。",
        "holdings": ["马格里布", "安达卢斯南部"],
        "members": [],
        "status": "已确定", "src": ["S0", "S2"],
        "notes": "本轮新增（推定补全）。",
    },
    {
        "id": "D_FATIMID", "name_zh": "法蒂玛", "name_de": "Fatimiden", "name_en": "Fatimids",
        "name_local": "الفاطميون", "type": "王朝", "polity": ["C_FATIMID", "C_EGYPT_REGION"],
        "origin": "北非伊斯玛仪派运动", "founded": "909", "ends": "1171",
        "religion": "伊斯兰教（伊斯玛仪派什叶派）", "religion_id": "R_ISLAM",
        "capital": "开罗", "capital_id": "P_CAIRO",
        "key_dates": ["909 建国", "969 建开罗", "1171 被萨拉丁推翻"],
        "overview": "什叶派哈里发王朝，以开罗为中心，使埃及成为独立的伊斯兰文明中心。",
        "holdings": ["埃及", "叙利亚南部", "汉志", "北非东部"],
        "members": [],
        "status": "已确定", "src": ["S1"],
        "notes": "本轮新增（推定补全）。",
    },
    {
        "id": "D_AYYUBID", "name_zh": "阿尤布", "name_de": "Ayyubiden", "name_en": "Ayyubids",
        "name_local": "الأيوبيون", "type": "王朝", "polity": ["C_AYYUBID", "C_EGYPT_REGION", "C_SYRIA"],
        "origin": "萨拉丁家族", "founded": "1171", "ends": "1250",
        "religion": "伊斯兰教（逊尼派）", "religion_id": "R_ISLAM",
        "capital": "开罗", "capital_id": "P_CAIRO",
        "key_dates": ["1171 推翻法蒂玛", "1187 收复耶路撒冷", "1250 被马穆鲁克取代"],
        "overview": "萨拉丁建立的王朝，统合埃及与叙利亚，是十字军东征时期穆斯林一方的主要政治体，也是法兰克东方学传统与军事传统的直接对位方。",
        "holdings": ["埃及", "叙利亚", "巴勒斯坦", "汉志", "也门"],
        "members": ["PE_SALADIN"],
        "status": "已确定", "src": ["S1"],
        "notes": "本轮新增（推定补全）。",
    },
    {
        "id": "D_MAMLUK", "name_zh": "马穆鲁克", "name_de": "Mamluken", "name_en": "Mamluks",
        "name_local": "المماليك", "type": "军事寡头王朝",
        "polity": ["C_MAMLUK", "C_EGYPT_REGION", "C_SYRIA"],
        "origin": "阿尤布王朝的军事奴隶精英", "founded": "1250", "ends": "1517",
        "religion": "伊斯兰教（逊尼派）", "religion_id": "R_ISLAM",
        "capital": "开罗", "capital_id": "P_CAIRO",
        "key_dates": ["1250 夺取政权", "1260 阻止蒙古西进", "1517 并入安纳托利亚突厥帝国"],
        "overview": "由军事奴隶精英建立的苏丹国。1260年阻止蒙古西进，使埃及与叙利亚免于被并入蒙古—金帐体系，从而在伊斯兰世界中保住了独立的政治传统。",
        "holdings": ["埃及", "叙利亚", "巴勒斯坦", "汉志"],
        "members": ["PE_BAIBARS"],
        "status": "已确定", "src": ["S1", "S4"],
        "notes": "本轮新增（推定补全）。",
    },
    {
        "id": "D_ABBASID", "name_zh": "阿拔斯", "name_de": "Abbasiden", "name_en": "Abbasids",
        "name_local": "العباسيون", "type": "王朝", "polity": ["C_ABBASID"],
        "origin": "先知家族哈希姆支系", "founded": "750", "ends": "1258",
        "religion": "伊斯兰教（逊尼派）", "religion_id": "R_ISLAM",
        "capital": "巴格达", "capital_id": "P_BAGHDAD",
        "key_dates": ["750 建国", "1258 巴格达陷落于蒙古西征军"],
        "overview": "以巴格达为中心的哈里发王朝，是伊斯兰世界逊尼派名义上的最高权威。其1258年的覆灭，是本世界线蒙古西征造成的最重大政治断裂之一。",
        "holdings": ["两河", "伊朗", "阿拉伯半岛东部"],
        "members": [],
        "status": "已确定", "src": ["S1"],
        "notes": "本轮新增（推定补全）。",
    },
    {
        "id": "D_PERSIAN_LINE", "name_zh": "波斯诸王朝序列", "name_de": "Persische Dynastienfolge",
        "name_en": "Persian dynastic sequence", "name_local": "سلسله‌های ایران",
        "type": "王朝序列（具体王朝名待定）", "polity": ["C_PERSIA"],
        "origin": "7世纪阿拉伯征服后，伊朗高原逐步形成独立的波斯政权传统；11世纪起由突厥—波斯混合王朝主导",
        "founded": "7世纪后逐步形成", "ends": "延续至今",
        "religion": "伊斯兰教（伊斯玛仪派 → 十二伊玛目派什叶派）", "religion_id": "R_ISLAM",
        "capital": "伊斯法罕（后期）", "capital_id": "P_ISFAHAN",
        "key_dates": ["7世纪 阿拉伯征服", "11世纪起 突厥—波斯混合王朝", "16世纪 什叶派确立为国教（推定）"],
        "overview": "伊朗高原的王朝序列。本世界线中波斯的特殊性在于：它既是伊斯兰文明的一部分，又处在伊斯兰文明东部边界的内侧——其东是伊斯兰中亚西部，再往东即西域佛教带。因此波斯承担了“伊斯兰世界东端锚点”的结构性功能。",
        "holdings": ["伊朗高原", "呼罗珊", "两河东部"],
        "members": ["PE_SCHAH_ISMAIL"],
        "status": "待定", "src": ["S1"],
        "notes": "本轮新增。具体王朝名（是否采用萨法维/萨曼/塞尔柱等命名）列为待定项 P26，等待用户裁定。此处只确定“波斯逐步形成什叶派国家传统”这一结构性方向。",
    },
    {
        "id": "D_OTTOMAN", "name_zh": "安纳托利亚突厥王朝", "name_de": "Anatolische Türkendynastie",
        "name_en": "Anatolian Turkish dynasty", "name_local": "Osmanlı Hanedanı",
        "type": "王朝", "polity": ["C_ANATOLIAN_TURKS"],
        "origin": "安纳托利亚西北部的突厥贝伊政权", "founded": "13世纪末",
        "ends": "延续至今（20世纪政体待定）",
        "religion": "伊斯兰教（逊尼派）", "religion_id": "R_ISLAM",
        "capital": "君士坦丁堡（1517年后）", "capital_id": "P_CONSTANTINOPLE",
        "key_dates": ["13世纪末 起家于安纳托利亚西北", "1517 取代马穆鲁克", "其后长期与海峡基督教政治体并存"],
        "overview": "安纳托利亚的突厥王朝。本世界线中它与基督教君士坦丁堡/海峡政治体长期并存对峙——“海峡是文明边界，而不是文明墙”（S1），因此两者不是简单的征服关系。",
        "holdings": ["安纳托利亚", "巴尔干南部", "叙利亚", "埃及", "汉志", "两河"],
        "members": ["PE_OSMAN_I"],
        "status": "待定", "src": ["S1"],
        "notes": "本轮新增。王朝名采用“安纳托利亚突厥王朝”这一描述性通名（对应实体名 Osmanlı Hanedanı）；正式王朝名与20世纪政体列为待定项 P27。",
    },
]

# ============================================================
# 人物补全（未具名 + 新增）
#   命名原则：法兰克人物用德语名；罗曼语地区用德语化拼写；
#             伊斯兰人物用阿拉伯/波斯/突厥语音译。
# ============================================================
PEOPLE = [
    # ---- 卡佩直系补全 ----
    {
        "id": "PE_PHILIP_III_WIFE", "name_zh": "腓力三世之妻（文档未具名）",
        "name_de": "Gemahlin Philipps III. (ungenannt)", "name_en": "Wife of Philip III (unnamed)",
        "title": "王后（推定）", "title_de": None,
        "dynasty": None, "dynasty_id": None, "country_id": "C_FRANKEN",
        "birth": "文档未载", "death": "文档未载", "reign": None,
        "positions": [],
        "deeds": ["文档仅以“腓力三世早逝，其子腓力四世、查理、路易均夭折或仅有女嗣”记载其子嗣，未具其名"],
        "family": {"husband": "PE_PHILIP_III", "sons": ["PE_PHILIP_IV"]},
        "context": "S0 仅记其存在（作为三子的母亲），未具名。",
        "status": "已确定", "src": ["S0"], "appendix": True,
        "notes": "文档未具名者，单列以保持家族关系网完整。",
    },
    {
        "id": "PE_CAPET_SONS", "name_zh": "查理、路易（腓力三世之子，文档未具名）",
        "name_de": "Karl und Ludwig (Söhne Philipps III., ungenannt)", "name_en": "Charles and Louis (sons of Philip III, unnamed)",
        "title": "卡佩王裔", "title_de": None,
        "dynasty": "卡佩", "dynasty_id": "D_CAPET", "country_id": "C_FRANKEN",
        "birth": "文档未载", "death": "1270年前后（夭折或仅有女嗣）", "reign": None,
        "positions": [],
        "deeds": ["与腓力四世同为腓力三世之子；均夭折或仅有女嗣，不构成萨利克法下的继承可能，导致卡佩直系断绝"],
        "family": {"father": "PE_PHILIP_III", "brothers": ["PE_PHILIP_IV"]},
        "context": "S0 只记名字未记生卒；二人合并为一条以保持家族关系网完整。",
        "status": "已确定", "src": ["S0"], "appendix": True,
        "notes": "文档未具名者（仅有名字，无生卒与事迹）。",
    },
    {
        "id": "PE_BRITTANY_DUKE", "name_zh": "布列塔尼公爵（1270年继承争夺者，文档未具名）",
        "name_de": "Herzog der Bretagne (ungenannt)", "name_en": "Duke of Brittany (unnamed)",
        "title": "布列塔尼公爵", "title_de": "Herzog der Bretagne",
        "dynasty": None, "dynasty_id": None, "country_id": "C_FRANKEN",
        "birth": "文档未载", "death": "文档未载", "reign": None,
        "positions": ["法兰克王位继承争夺者"],
        "deeds": ["1270年前后作为卡佩继承争夺者之一提出主张，未成功"],
        "family": {}, "context": "S0 只记头衔未记姓名。",
        "status": "已确定", "src": ["S0"], "appendix": True,
        "notes": "文档未具名者。",
    },
    {
        "id": "PE_NORMANDY_DUKE", "name_zh": "诺曼底公爵（1272年决战失败者，文档未具名）",
        "name_de": "Herzog der Normandie (ungenannt)", "name_en": "Duke of Normandy (unnamed)",
        "title": "诺曼底公爵", "title_de": "Herzog der Normandie",
        "dynasty": None, "dynasty_id": None, "country_id": "C_ENGLAND_NORMANDY",
        "birth": "文档未载", "death": "文档未载", "reign": None,
        "positions": ["诺曼底公爵", "诺曼底-英格兰联军统帅（推定）"],
        "deeds": ["1272年在一次决战中被鲁道夫击败，诺曼底-英格兰联军失去法兰西岛与香槟，英格兰-诺曼底被逐出大陆"],
        "family": {}, "context": "S0/S1 只记头衔未记姓名。",
        "status": "已确定", "src": ["S0", "S1"], "appendix": True,
        "notes": "文档未具名者。",
    },
    {
        "id": "PE_ALBRECHT_II_SON_IN_LAW", "name_zh": "阿尔布雷希特二世之女婿（法兰克贵族推举对象，文档未具名）",
        "name_de": "Schwiegersohn Albrechts II. (ungenannt)", "name_en": "Son-in-law of Albrecht II (unnamed)",
        "title": "法兰克贵族推举的王位继承人（推定）", "title_de": None,
        "dynasty": None, "dynasty_id": None, "country_id": "C_FRANKEN",
        "birth": "文档未载", "death": "文档未载", "reign": None,
        "positions": ["法兰克贵族推举对象"],
        "deeds": ["1356年法兰克贵族要求其继承法兰克王位，德意志选侯坚持选举德意志诸侯为皇帝；教皇介入后以《法兰克福宪章》的双轨制妥协解决"],
        "family": {"wife": "PE_ALBRECHT_II_DAUGHTER"},
        "context": "S0 只记身份未记姓名。",
        "status": "已确定", "src": ["S0"], "appendix": True,
        "notes": "文档未具名者。",
    },
    {
        "id": "PE_BURGUNDY_COUNT", "name_zh": "勃艮第伯爵（鲁道夫之岳父，文档未具名）",
        "name_de": "Graf von Burgund (ungenannt)", "name_en": "Count of Burgundy (unnamed)",
        "title": "勃艮第伯爵", "title_de": "Graf von Burgund",
        "dynasty": "勃艮第", "dynasty_id": "D_BURGUNDY", "country_id": "C_FRANKEN",
        "birth": "文档未载", "death": "文档未载", "reign": None,
        "positions": ["勃艮第伯爵"],
        "deeds": ["其女嫁与鲁道夫，使鲁道夫掌握东部军事资源，成为其当选法兰克国王的重要资本"],
        "family": {"daughter": "PE_RUDOLF_WIFE"},
        "context": "S0/S1 只记身份未记姓名。",
        "status": "已确定", "src": ["S0", "S1"], "appendix": True,
        "notes": "文档未具名者。",
    },
    {
        "id": "PE_REIMS_ARCHBISHOP", "name_zh": "雷姆斯大主教（1272年为鲁道夫加冕者，文档未具名）",
        "name_de": "Erzbischof von Reims (ungenannt)", "name_en": "Archbishop of Reims (unnamed)",
        "title": "雷姆斯大主教", "title_de": "Erzbischof von Reims",
        "dynasty": None, "dynasty_id": None, "country_id": "C_FRANKEN",
        "birth": "文档未载", "death": "文档未载", "reign": None,
        "positions": ["雷姆斯大主教（法兰克国王的加冕主持者）"],
        "deeds": ["1272年在部分贵族见证下为鲁道夫加冕为“法兰克人的国王”"],
        "family": {}, "context": "S0/S1 只记职务未记姓名。",
        "status": "已确定", "src": ["S0", "S1"], "appendix": True,
        "notes": "文档未具名者。",
    },
    {
        "id": "PE_JOHANNA_VON_ARKON", "name_zh": "约翰娜·冯·阿尔孔", "name_de": "Johanna von Arkon",
        "name_en": "Johanna von Arkon", "title": "法兰克抗伊比利亚民兵领袖（推定）",
        "title_de": "Anführerin der fränkischen Milizen",
        "dynasty": None, "dynasty_id": None, "country_id": "C_FRANKEN",
        "birth": "推定 1410年前后", "death": "推定 1431年（本轮新增，可调整）",
        "reign": None,
        "positions": ["民兵领袖", "后为法兰克王家教会封圣对象（推定）"],
        "deeds": [
            "在伊比利亚（阿拉贡—奥克方向）压力最大的年代，率法兰克民兵解围奥尔伦（Orlen）",
            "推动鲁道夫系之后的法兰克王权在香槟—卢瓦尔一线重新站稳",
            "后被法兰克王家教会封圣，成为“天主教法兰克民族意识”的象征之一",
        ],
        "family": {},
        "context": "以现实史的贞德为原型，按本世界线改造：法兰克为西部日耳曼政治体、天主教，其对手由英格兰改为伊比利亚—奥克方向的压力。姓名按德语化处理（Arkon ← Arc）。",
        "status": "待定", "src": ["S0"],
        "notes": "本轮新增（推定人物）。原型：贞德。用途：为法兰克“天主教民族意识”提供人物锚点（对应 S0 所记雷姆斯神学院研究“天主教法兰克民族意识”）。生卒年为推定，待用户裁定。",
    },
    {
        "id": "PE_KARDINAL_RICHELIEU", "name_zh": "帝国首相黎塞留", "name_de": "Reichskanzler Richelieu",
        "name_en": "Imperial Chancellor Richelieu", "title": "法兰克帝国首相 / 枢机（推定）",
        "title_de": "Reichskanzler und Kardinal",
        "dynasty": None, "dynasty_id": None, "country_id": "C_FRANKEN",
        "birth": "推定 1585年", "death": "推定 1642年（本轮新增，可调整）",
        "reign": None,
        "positions": ["法兰克帝国首相", "枢机", "帕里斯王家学院赞助人"],
        "deeds": [
            "在宗教战争后期主持法兰克战时财政与外交，支撑两线作战的僵局",
            "确立“法兰克优先于帝国”的国务路线，为1871年法兰克与德意志王冠分离埋下长期伏笔",
            "赞助帕里斯王家学院，推动法兰克东方学传统（对应 S1《法兰克与近东》）",
        ],
        "family": {},
        "context": "以现实史的黎塞留为原型，按本世界线改造：法兰克为天主教哈布斯堡国家，其国务路线以“法兰克本位”对抗双王冠体制。姓名保留罗曼语姓氏并加德语头衔。",
        "status": "待定", "src": ["S0", "S1"],
        "notes": "本轮新增（推定人物）。原型：黎塞留。用途：解释 S0 所记“法兰克天主教贵族要求皇帝停战”与法兰克宪政早熟的政治操作者角色。",
    },
    {
        "id": "PE_ABD_AL_RAHMAN_III", "name_zh": "阿卜杜勒·拉赫曼三世",
        "name_de": "Abd ar-Rahman III.", "name_en": "Abd al-Rahman III",
        "name_local": "عبد الرحمن الثالث",
        "title": "科尔多瓦哈里发", "title_de": "Kalif von Córdoba",
        "dynasty": "伍麦叶（西班牙支系）", "dynasty_id": "D_UMAYYAD", "country_id": "C_CORDOBA",
        "birth": "891", "death": "961", "reign": "912 — 961（929年自立哈里发）",
        "positions": ["科尔多瓦埃米尔（912起）", "科尔多瓦哈里发（929起）"],
        "deeds": ["929年自立为哈里发，与阿拔斯、法蒂玛三足鼎立", "使科尔多瓦成为西欧最繁盛的城市与文化中心"],
        "family": {},
        "context": "安达卢斯穆斯林政权的最高点；其自立哈里发是伊斯兰世界三分格局的起点。",
        "status": "已确定", "src": ["S0", "S2"],
        "notes": "本轮新增（推定补全）。生卒年采通行史实。",
    },
    {
        "id": "PE_ALFONS_X", "name_zh": "阿方索十世", "name_de": "Alfons X. von Kastilien",
        "name_en": "Alfonso X of Castile", "name_local": "Alfonso X",
        "title": "卡斯蒂利亚国王", "title_de": "König von Kastilien",
        "dynasty": None, "dynasty_id": None, "country_id": "C_SPAIN_ARAGON",
        "birth": "1221", "death": "1284", "reign": "1252 — 1284",
        "positions": ["卡斯蒂利亚国王", "神圣罗马帝国皇位候选人（推定）"],
        "deeds": [
            "推动卡斯蒂利亚在伊比利亚的扩张，是伊比利亚统一进程的早期阶段之一",
            "主持编纂《七章法典》（Siete Partidas）与天文表，是伊比利亚罗曼语高文化的代表",
        ],
        "family": {},
        "context": "伊比利亚统一进程早期的代表性君主。按世界线口径，其名采用德式转写（Alfons）。",
        "status": "已确定", "src": ["S2"],
        "notes": "本轮新增（推定补全）。用途：为 S2 所记“伊比利亚各基督教王国逐步统一”提供人物锚点。",
    },
    {
        "id": "PE_SALADIN", "name_zh": "萨拉丁", "name_de": "Salah ad-Din",
        "name_en": "Saladin", "name_local": "صلاح الدين",
        "title": "阿尤布苏丹", "title_de": "Sultan der Ayyubiden",
        "dynasty": "阿尤布", "dynasty_id": "D_AYYUBID", "country_id": "C_AYYUBID",
        "birth": "1137", "death": "1193", "reign": "1171 — 1193",
        "positions": ["埃及与叙利亚苏丹", "阿尤布王朝创立者"],
        "deeds": [
            "1171年推翻法蒂玛王朝，埃及转入逊尼派",
            "统合埃及与叙利亚，成为十字军东征时期穆斯林一方的主要政治体",
            "1187年收复耶路撒冷",
        ],
        "family": {},
        "context": "法兰克东方学传统与军事传统的主要对位人物（库尔德裔）。",
        "status": "已确定", "src": ["S1"],
        "notes": "本轮新增（推定补全）。",
    },
    {
        "id": "PE_BAIBARS", "name_zh": "拜巴尔斯", "name_de": "Baibars", "name_en": "Baibars",
        "name_local": "الظاهر بيبرس",
        "title": "马穆鲁克苏丹", "title_de": "Mamlukensultan",
        "dynasty": "马穆鲁克", "dynasty_id": "D_MAMLUK", "country_id": "C_MAMLUK",
        "birth": "1223年前后", "death": "1277", "reign": "1260 — 1277",
        "positions": ["马穆鲁克苏丹"],
        "deeds": [
            "1260年击败蒙古西征军，阻止蒙古—金帐体系向黎凡特与埃及扩张",
            "巩固马穆鲁克在埃及与叙利亚的统治",
            "在东地中海与红海贸易中确立马穆鲁克的中介地位",
        ],
        "family": {},
        "context": "本世界线中蒙古文明遗产极为深厚（S4），因此马穆鲁克对蒙古的阻击具有世界史意义：它划出了蒙古—金帐体系的西侧界线。",
        "status": "已确定", "src": ["S1", "S4"],
        "notes": "本轮新增（推定补全）。",
    },
    {
        "id": "PE_SCHAH_ISMAIL", "name_zh": "沙阿伊斯玛仪", "name_de": "Schah Ismail",
        "name_en": "Shah Ismail", "name_local": "شاه اسماعیل",
        "title": "波斯沙阿（推定）", "title_de": "Schah von Persien",
        "dynasty": "波斯诸王朝", "dynasty_id": "D_PERSIAN_LINE", "country_id": "C_PERSIA",
        "birth": "推定 1487年", "death": "推定 1524年（本轮新增，可调整）",
        "reign": "推定 1501 — 1524",
        "positions": ["波斯沙阿", "什叶派国教的奠基者（推定）"],
        "deeds": [
            "统一伊朗高原，确立波斯作为伊斯兰世界第二极的地位",
            "将什叶派确立为国教，使波斯与逊尼派的阿拉伯—安纳托利亚体系长期并立",
            "其东界止于伊斯兰中亚西部，再东即西域佛教带——正对应 S1 所定的“伊斯兰文明东部边界”",
        ],
        "family": {},
        "context": "以现实史的萨法维王朝开国者伊斯玛仪一世为原型。用途：为“波斯逐步形成什叶派国家传统”提供人物锚点。",
        "status": "待定", "src": ["S1"],
        "notes": "本轮新增（推定人物）。原型：伊斯玛仪一世。生卒年与王朝名均待定（见待定项 P26）。",
    },
    {
        "id": "PE_OSMAN_I", "name_zh": "奥斯曼一世", "name_de": "Osman I.", "name_en": "Osman I",
        "name_local": "عثمان بن ارطغرل",
        "title": "安纳托利亚突厥贝伊（推定）", "title_de": "Bey der anatolischen Türken",
        "dynasty": "安纳托利亚突厥王朝", "dynasty_id": "D_OTTOMAN", "country_id": "C_ANATOLIAN_TURKS",
        "birth": "1258年前后", "death": "1326年前后", "reign": "推定 1299 — 1326",
        "positions": ["安纳托利亚西北部贝伊", "安纳托利亚突厥王朝的奠基者"],
        "deeds": [
            "在安纳托利亚西北部起家，为后来取代马穆鲁克、统合近东的突厥帝国奠基",
            "其政权与基督教君士坦丁堡/海峡政治体长期对峙共处",
        ],
        "family": {},
        "context": "本世界线中安纳托利亚是伊斯兰力量向欧洲方向的主要压力来源，而海峡则是“文明边界而非文明墙”。",
        "status": "待定", "src": ["S1"],
        "notes": "本轮新增（推定人物）。王朝名与20世纪政体待定（见待定项 P27）。",
    },
    {
        "id": "PE_ISABELLA_VON_KASTILIEN", "name_zh": "伊莎贝拉·冯·卡斯蒂利亚",
        "name_de": "Isabella von Kastilien", "name_en": "Isabella of Castile",
        "name_local": "Isabel de Castilla",
        "title": "卡斯蒂利亚女王（推定）", "title_de": "Königin von Kastilien",
        "dynasty": None, "dynasty_id": None, "country_id": "C_SPAIN_ARAGON",
        "birth": "推定 1451年", "death": "推定 1504年（本轮新增，可调整）",
        "reign": "推定 1474 — 1504",
        "positions": ["卡斯蒂利亚女王", "伊比利亚统一的推动者（推定）"],
        "deeds": [
            "与阿拉贡王权联合，完成伊比利亚半岛主要部分的统一（推定）",
            "推动对半岛南部穆斯林政权的最后征服（推定）",
            "其政策开启了伊比利亚南下北非驱逐穆斯林的进程（推定）",
        ],
        "family": {},
        "context": "姓名按德语化处理（Isabella von Kastilien）。用途：为“西班牙-阿拉贡逐步统一伊比利亚”提供人物锚点。",
        "status": "待定", "src": ["S2"],
        "notes": "本轮新增（推定人物）。原型：伊莎贝拉一世。生卒年与事迹细节待用户裁定。",
    },
    {
        "id": "PE_IBERIA_KING_FOUNDER", "name_zh": "伊比利亚王国开国君主（本轮新增，姓名待定）",
        "name_de": "Gründerkönig von Iberien (Name offen)", "name_en": "Founding King of Iberia (name pending)",
        "title": "伊比利亚国王（推定）", "title_de": "König von Iberien",
        "dynasty": "伊比利亚王朝", "dynasty_id": "D_IBERIA_DYNASTY", "country_id": "C_IBERIAN_KINGDOM",
        "birth": "文档未载（本轮新增）", "death": "文档未载（本轮新增）",
        "reign": "推定 16世纪（伊比利亚统一完成后）",
        "positions": ["伊比利亚国王"],
        "deeds": [
            "宣布伊比利亚各基督教王国统一为伊比利亚王国（推定）",
            "确立对北非西部的统治，开始长期基督教化与欧洲化进程（推定）",
        ],
        "family": {},
        "context": "用户本轮补充“逐步统一伊比利亚，并南下北非驱逐穆斯林，建立伊比利亚王国”。此条目为该建国行为的占位人物，姓名与具体年份等待用户裁定。",
        "status": "待定", "src": ["S2"],
        "notes": "本轮新增（占位）。姓名、生卒年、统一的确切年份均待定（见待定项 P28）。",
    },
]

# ============================================================
# 新增事件
# ============================================================
EVENTS = [
    {
        "id": "E_0929_CORDOBA", "year": 929, "year_text": "929", "epoch": "8—11世纪：伊斯兰伊比利亚",
        "name_zh": "科尔多瓦自立哈里发", "name_de": "Selbsterhebung zum Kalifat von Córdoba",
        "name_en": "Self-proclamation of the Caliphate of Córdoba",
        "region": "伊比利亚南部（科尔多瓦）",
        "country_ids": ["C_CORDOBA", "C_SPAIN_ARAGON"],
        "persons": ["PE_ABD_AL_RAHMAN_III"],
        "summary": "阿卜杜勒·拉赫曼三世自立为哈里发，使安达卢斯在政治上与阿拔斯、法蒂玛三足鼎立。",
        "outcome": "伊斯兰世界形成科尔多瓦、巴格达、开罗（法蒂玛）三哈里发并立格局；安达卢斯进入文明鼎盛期。",
        "causes": [], "effects": ["E_1031_TAIFAS"],
        "status": "已确定", "src": ["S0", "S2"],
        "notes": "本轮新增（推定补全），用于支撑 S2 第十八节“收复失地运动”起点之前的伊比利亚史。",
    },
    {
        "id": "E_1031_TAIFAS", "year": 1031, "year_text": "1031", "epoch": "11世纪：安达卢斯分裂",
        "name_zh": "科尔多瓦哈里发国分裂为诸泰法", "name_de": "Zerfall in die Taifa-Königreiche",
        "name_en": "Collapse into the Taifa kingdoms",
        "region": "伊比利亚南部",
        "country_ids": ["C_CORDOBA", "C_ALMOHAD", "C_SPAIN_ARAGON"],
        "persons": [],
        "summary": "科尔多瓦哈里发国分裂为诸多泰法小国，安达卢斯政治碎片化；北非的穆拉比特与穆瓦希德两王朝先后渡海接管。",
        "outcome": "安达卢斯由统一转为分裂，为北方基督教诸王国的推进提供条件；北非柏柏尔王朝介入伊比利亚。",
        "causes": ["E_0929_CORDOBA"], "effects": ["E_1212_LAS_NAVAS", "E_RECONQUISTA"],
        "status": "已确定", "src": ["S0", "S2"],
        "notes": "本轮新增（推定补全）。",
    },
    {
        "id": "E_1212_LAS_NAVAS", "year": 1212, "year_text": "1212", "epoch": "13世纪：收复失地运动的转折",
        "name_zh": "穆瓦希德在伊比利亚战败", "name_de": "Niederlage der Almohaden in Iberien",
        "name_en": "Almohad defeat in Iberia",
        "region": "伊比利亚南部",
        "country_ids": ["C_ALMOHAD", "C_SPAIN_ARAGON", "C_MAGHREB"],
        "persons": [],
        "summary": "伊比利亚各基督教王国联军击败穆瓦希德，北非柏柏尔王朝在伊比利亚的统治崩溃。",
        "outcome": "收复失地运动进入决定性阶段；伊比利亚各基督教王国得以逐步统一，并开始南下北非驱逐穆斯林。",
        "causes": ["E_1031_TAIFAS"], "effects": ["E_RECONQUISTA", "E_IBERIAN_UNIFICATION"],
        "status": "已确定", "src": ["S0", "S2"],
        "notes": "本轮新增（推定补全）。",
    },
    {
        "id": "E_RECONQUISTA", "year": 1300, "year_text": "8—15世纪（决定性阶段1212—1492）", "epoch": "8—15世纪：收复失地运动",
        "name_zh": "收复失地运动", "name_de": "Reconquista", "name_en": "Reconquista",
        "region": "伊比利亚半岛",
        "country_ids": ["C_SPAIN_ARAGON", "C_ALMOHAD", "C_CORDOBA", "C_MAGHREB"],
        "persons": ["PE_ALFONS_X", "PE_ISABELLA_VON_KASTILIEN"],
        "summary": "伊比利亚各基督教王国历时数百年逐步收复半岛，驱逐穆斯林政权。S2 第十八节以此作为伊比利亚历史链条的起点，并由此形成“共同基督教/伊比利亚身份”。",
        "outcome": "半岛穆斯林政权被逐出；伊比利亚形成以天主教为立国原则的共同身份，并转向南下北非。",
        "causes": ["E_1212_LAS_NAVAS", "E_1031_TAIFAS"],
        "effects": ["E_IBERIAN_UNIFICATION", "E_MAGHREB_CHRISTIANISATION"],
        "war_id": "W_RECONQUISTA",
        "status": "已确定", "src": ["S0", "S2"],
        "notes": "S2 第十八节明列“收复失地运动↓共同基督教/伊比利亚身份”为伊比利亚历史政治逻辑的第一环。",
    },
    {
        "id": "E_IBERIAN_UNIFICATION", "year": 1500, "year_text": "15—16世纪（推定）", "epoch": "15—16世纪：伊比利亚统一",
        "name_zh": "伊比利亚统一与伊比利亚王国建立",
        "name_de": "Iberische Einigung und Gründung des Königreichs Iberien",
        "name_en": "Iberian unification and the founding of the Kingdom of Iberia",
        "region": "伊比利亚半岛",
        "country_ids": ["C_SPAIN_ARAGON", "C_IBERIAN_KINGDOM", "C_OCCITAN_KINGDOM"],
        "persons": ["PE_ISABELLA_VON_KASTILIEN", "PE_IBERIA_KING_FOUNDER"],
        "summary": "由西班牙-阿拉贡（及奥克王国）为起点，伊比利亚各基督教王国逐步统一，建立伊比利亚王国。",
        "outcome": "伊比利亚成为统一的中央集权君主国；此后转向南下北非，驱逐穆斯林并长期统治、基督教化马格里布。",
        "causes": ["E_RECONQUISTA"],
        "effects": ["E_MAGHREB_CHRISTIANISATION", "E_1789_REVOLUTION"],
        "status": "已确定", "src": ["S2"],
        "notes": "本轮新增（用户补充）。统一的确切年份与开国君主的姓名待定（见待定项 P28）。",
    },
    {
        "id": "E_MAGHREB_CHRISTIANISATION", "year": 1550,
        "year_text": "16—20世纪（长期过程）", "epoch": "16—20世纪：北非西部的基督教化",
        "name_zh": "南下北非与马格里布的基督教化、欧洲化",
        "name_de": "Vordringen nach Nordafrika und Christianisierung des Maghreb",
        "name_en": "Southward expansion into North Africa and the Christianisation of the Maghreb",
        "region": "北非西部（马格里布）",
        "country_ids": ["C_IBERIAN_KINGDOM", "C_MAGHREB", "C_IBERIA"],
        "persons": [],
        "summary": "伊比利亚南下北非驱逐穆斯林，此后长期统治并基督教化、欧洲化马格里布。S2 明确该地区“没有特殊宪制地位”，与半岛同属一个国家行政体系。",
        "outcome": "北非西部成为伊比利亚本土的一部分；撒哈拉从此承担文明分界功能——以北西部划入欧洲，以东划入亚洲。",
        "causes": ["E_IBERIAN_UNIFICATION"],
        "effects": ["E_1960_MULTIPOLAR"],
        "war_id": "W_RECONQUISTA",
        "status": "已确定", "src": ["S0", "S2"],
        "notes": "S0 记伊比利亚“统治北非西部”；S2 第19/20/29节明确其宪制地位与文明归属。",
    },
    {
        "id": "E_CRUSADES", "year": 1096, "year_text": "11—13世纪", "epoch": "11—13世纪：十字军东征",
        "name_zh": "十字军东征", "name_de": "Kreuzzüge", "name_en": "The Crusades",
        "region": "黎凡特、东地中海",
        "country_ids": ["C_FRANKISH_ROMANCE", "C_PAPAL", "C_AYYUBID", "C_FATIMID", "C_SYRIA", "C_BYZANTIUM", "C_ANATOLIAN_TURKS"],
        "persons": ["PE_SALADIN"],
        "summary": "**法兰西罗曼王国**（1270 年前大陆北部的罗曼语政治体，即十字军的发动者）与教皇国向黎凡特发动的军事远征。1270 年卡佩绝嗣、1272 年哈布斯堡入主之后，大陆北部的十字军遗产与地中海—黎凡特传统由日耳曼的法兰克承继，并最终形成帕里斯的东方学传统（S1）。",
        "outcome": "十字军遗产经法兰西罗曼王国转入日耳曼的法兰克，使法兰克成为「连接西欧、地中海、黎凡特与德意志世界的文明边界国家」；黎凡特穆斯林政权（法蒂玛、阿尤布、马穆鲁克）在对抗中完成整合。",
        "causes": [], "effects": ["E_FRANKISH_ORIENTALISM", "E_1291_ACRE"],
        "war_id": "W_CRUSADES",
        "status": "已确定", "src": ["S1"],
        "notes": "本轮新增（推定补全）。S1《法兰克与近东》一节明定法兰克因此成为“欧洲研究东方世界的重要文明”。",
    },
    {
        "id": "E_1291_ACRE", "year": 1291, "year_text": "1291", "epoch": "13世纪：十字军据点的终结",
        "name_zh": "黎凡特沿岸据点失守", "name_de": "Verlust der Levante-Stützpunkte",
        "name_en": "Loss of the Levantine strongholds",
        "region": "黎凡特沿岸",
        "country_ids": ["C_FRANKEN", "C_MAMLUK", "C_SYRIA"],
        "persons": [],
        "summary": "马穆鲁克夺取黎凡特沿岸最后据点，法兰克在地中海东岸的军事存在终结。",
        "outcome": "法兰克转为以商业、传教与学术方式维持近东联系——这正是 S1 所记“法兰克东方学传统”的由来。",
        "causes": ["E_CRUSADES"], "effects": ["E_FRANKISH_ORIENTALISM"],
        "status": "已确定", "src": ["S1"],
        "notes": "本轮新增（推定补全）。",
    },
    {
        "id": "E_FRANKISH_ORIENTALISM", "year": 1400,
        "year_text": "14世纪以后（长时段）", "epoch": "14世纪以后：法兰克东方学",
        "name_zh": "法兰克东方学传统的形成",
        "name_de": "Herausbildung der fränkischen Orientalistik",
        "name_en": "Formation of the Frankish Orientalist tradition",
        "region": "帕里斯、劳格登",
        "country_ids": ["C_FRANKEN", "C_SYRIA", "C_MAGHREB", "C_EGYPT_REGION"],
        "persons": [],
        "summary": "法兰克承继了**法兰西罗曼王国**的十字军遗产（天主教、地中海传统、北非与黎凡特传统影响），加上帕里斯自身的神学、历史、东方学传统，发展出自己的东方学学术传统。",
        "outcome": "法兰克成为“连接西欧、地中海、黎凡特与德意志世界的文明边界国家”，而非简单的“德国西边的法国替代品”。",
        "causes": ["E_1291_ACRE"],
        "effects": [],
        "status": "已确定", "src": ["S1"],
        "notes": "S1《法兰克与近东》一节明定此方向。",
    },
    {
        "id": "E_MAMLUK_MONGOL", "year": 1260, "year_text": "1260", "epoch": "13世纪：蒙古西征的界线",
        "name_zh": "马穆鲁克阻止蒙古西进", "name_de": "Mamlukischer Sieg über die Mongolen",
        "name_en": "Mamluk halt of the Mongol advance",
        "region": "黎凡特",
        "country_ids": ["C_MAMLUK", "C_MONGOL_EMPIRE", "C_ABBASID", "C_SYRIA", "C_EGYPT_REGION"],
        "persons": ["PE_BAIBARS"],
        "summary": "马穆鲁克击败蒙古西征军，并在此之前后目睹巴格达（1258）陷落。",
        "outcome": "蒙古—金帐体系的西侧界线被划定；埃及与叙利亚保住独立的伊斯兰政治传统，未被并入蒙古体系。这与 S4 所记“蒙古文明遗产从太平洋延伸到东欧森林地带”形成对照——其南界与西界正是此处。",
        "causes": ["E_1200_MONGOL"], "effects": ["E_1500_ROS_UHLUS"],
        "war_id": "W_MONGOL_EXPANSION",
        "status": "已确定", "src": ["S1", "S4"],
        "notes": "本轮新增（推定补全），用于标定蒙古文明遗产区的南界。",
    },
    {
        "id": "E_1517_MAMLUK_END", "year": 1517, "year_text": "1517", "epoch": "16世纪：近东格局重组",
        "name_zh": "安纳托利亚突厥帝国取代马穆鲁克",
        "name_de": "Ende des Mamlukensultanats",
        "name_en": "End of the Mamluk Sultanate",
        "region": "埃及、叙利亚、汉志",
        "country_ids": ["C_ANATOLIAN_TURKS", "C_MAMLUK", "C_EGYPT_REGION", "C_SYRIA", "C_ARABIA"],
        "persons": ["PE_OSMAN_I"],
        "summary": "安纳托利亚的突厥帝国吞并马穆鲁克统治的埃及与叙利亚，并取得汉志两圣地的宗主权。",
        "outcome": "近东整合为单一的逊尼派伊斯兰帝国，与波斯的什叶派体系形成长期并立格局。",
        "causes": ["E_1500_ROS_UHLUS"], "effects": ["E_1960_MULTIPOLAR"],
        "status": "已确定", "src": ["S1"],
        "notes": "本轮新增（推定补全）。",
    },
    {
        "id": "E_1501_PERSIA_SHIITE", "year": 1501, "year_text": "16世纪（推定）", "epoch": "16世纪：波斯什叶派国家",
        "name_zh": "波斯确立什叶派国家传统",
        "name_de": "Etablierung der schiitischen Staatstradition in Persien",
        "name_en": "Establishment of Persia's Shi'ite state tradition",
        "region": "伊朗高原",
        "country_ids": ["C_PERSIA", "C_ANATOLIAN_TURKS", "C_ABBASID"],
        "persons": ["PE_SCHAH_ISMAIL"],
        "summary": "波斯统一并确立什叶派为国教，成为伊斯兰世界内部与逊尼派阿拉伯—安纳托利亚体系并立的第二极。",
        "outcome": "伊斯兰世界形成逊尼（阿拉伯—安纳托利亚）与什叶（波斯）双极结构；波斯的东界止于伊斯兰中亚西部，再东即西域佛教带。",
        "causes": ["E_1200_MONGOL"], "effects": ["E_1960_MULTIPOLAR"],
        "status": "待定", "src": ["S1"],
        "notes": "本轮新增。具体王朝名与年份待定（见待定项 P26）。",
    },
]

# ============================================================
# 新增战争
# ============================================================
WARS = [
    {
        "id": "W_RECONQUISTA", "name_zh": "收复失地运动与南下北非（8—16世纪）",
        "name_de": "Reconquista und Vordringen nach Nordafrika",
        "name_en": "Reconquista and the southward expansion into North Africa",
        "time_start": "1212", "time_end": "1550",
        "time_text": "8—16世纪（决定性阶段1212—16世纪）", "epoch": "8—16世纪：伊比利亚与马格里布",
        "side_a": {"name": "伊比利亚基督教诸王国（后为伊比利亚王国）",
                   "members": ["卡斯蒂利亚", "阿拉贡", "葡萄牙", "纳瓦拉", "奥克王国（早期）"],
                   "country_ids": ["C_SPAIN_ARAGON", "C_IBERIAN_KINGDOM", "C_OCCITAN_KINGDOM"]},
        "side_b": {"name": "伊比利亚与马格里的穆斯林政权",
                   "members": ["诸泰法", "穆拉比特", "穆瓦希德", "马格里布诸王朝"],
                   "country_ids": ["C_ALMOHAD", "C_MAGHREB"]},
        "other_claimants": ["科尔多瓦哈里发国（929—1031，本战争的前期对位方，其终结早于本战争的决定性阶段）"],
        "causes_text": ["伊比利亚各基督教王国的扩张", "安达卢斯1031年后的政治碎片化", "天主教共同身份的形成"],
        "key_battles": ["1212年穆瓦希德在伊比利亚战败（收复失地运动的转折点）"],
        "result": "伊比利亚各基督教王国完成半岛统一并南下北非驱逐穆斯林，建立伊比利亚王国；马格里布被长期统治、基督教化与欧洲化",
        "consequence": ["伊比利亚成为统一的中央集权君主国", "北非西部成为伊比利亚本土一部分（无特殊宪制地位）", "撒哈拉成为文明分界线：以北西部属欧洲、以东属亚洲", "奥克王国被卷入伊比利亚的政治轨道"],
        "treaty": None, "treaty_id": None,
        "status": "已确定", "src": ["S0", "S2"],
        "notes": "本轮新增（用户补充 + 推定补全）。",
    },
    {
        "id": "W_CRUSADES", "name_zh": "十字军东征（11—13世纪）", "name_de": "Kreuzzüge",
        "name_en": "The Crusades",
        "time_start": "1096", "time_end": "1291",
        "time_text": "11—13世纪", "epoch": "11—13世纪：十字军东征",
        "side_a": {"name": "法兰西罗曼王国—教皇国一方（1270 年前大陆北部的罗曼语政治体）",
                   "members": ["法兰西罗曼王国（十字军发动者）", "教皇国", "北意大利天主教城市"],
                   "country_ids": ["C_FRANKISH_ROMANCE", "C_PAPAL"]},
        "side_b": {"name": "黎凡特穆斯林政权",
                   "members": ["法蒂玛哈里发国", "阿尤布苏丹国", "马穆鲁克苏丹国", "叙利亚地区"],
                   "country_ids": ["C_FATIMID", "C_AYYUBID", "C_MAMLUK", "C_SYRIA"]},
        "other_claimants": ["拜占庭 / 君士坦丁堡海峡政治体", "安纳托利亚突厥帝国"],
        "causes_text": ["法兰克的天主教扩张动力", "教皇国主导的远征号召", "东地中海商路控制权"],
        "key_battles": ["1187年萨拉丁收复耶路撒冷", "1291年黎凡特沿岸最后据点失守"],
        "result": "穆斯林一方最终保有黎凡特；法兰克在地中海东岸的军事存在终结",
        "consequence": ["十字军遗产由法兰西罗曼王国转入日耳曼的法兰克", "法兰克由此承继地中海传统、北非与黎凡特传统影响、帕里斯东方学传统", "法兰克成为“连接西欧、地中海、黎凡特与德意志世界的文明边界国家”", "阿尤布与马穆鲁克在对抗中完成整合"],
        "treaty": None, "treaty_id": None,
        "status": "已确定", "src": ["S1"],
        "notes": "本轮新增（推定补全）。S1《法兰克与近东》明定法兰克由此成为东方学研究的重要文明。",
    },
]

# ============================================================
# 新增地点
# ============================================================
PLACES = [
    {"id": "P_TOLEDO", "type": "古都（推定）", "zh": "托莱多", "real": "Toledo", "de": "Toledo",
     "en": "Toledo", "es": "Toledo", "note": "伊比利亚王国首都（推定，文档未指定）",
     "country_id": "C_IBERIAN_KINGDOM", "src": ["S2"]},
    {"id": "P_CORDOBA", "type": "哈里发国都城", "zh": "科尔多瓦", "real": "Córdoba", "de": "Córdoba",
     "en": "Cordoba", "es": "Córdoba", "ar": "قرطبة", "note": "科尔多瓦哈里发国首都",
     "country_id": "C_CORDOBA", "src": ["S0"]},
    {"id": "P_MARRAKECH", "type": "王朝都城", "zh": "马拉喀什", "real": "Marrakesh", "de": "Marrakesch",
     "en": "Marrakesh", "fr": "Marrakech", "ar": "مراكش", "note": "穆瓦希德王朝首都",
     "country_id": "C_ALMOHAD", "src": ["S0"]},
    {"id": "P_FEZ", "type": "区域中心", "zh": "非斯", "real": "Fez", "de": "Fes", "en": "Fez",
     "fr": "Fès", "ar": "فاس", "note": "马格里布区域中心", "country_id": "C_MAGHREB", "src": ["S0"]},
    {"id": "P_TUNIS", "type": "区域中心", "zh": "突尼斯", "real": "Tunis", "de": "Tunis",
     "en": "Tunis", "fr": "Tunis", "ar": "تونس", "note": "马格里布东部区域中心",
     "country_id": "C_MAGHREB", "src": ["S0"]},
    {"id": "P_CAIRO", "type": "王朝都城", "zh": "开罗", "real": "Cairo", "de": "Kairo",
     "en": "Cairo", "ar": "القاهرة", "note": "法蒂玛、阿尤布、马穆鲁克诸王朝首都",
     "country_id": "C_EGYPT_REGION", "src": ["S1"]},
    {"id": "P_DAMASCUS", "type": "区域中心", "zh": "大马士革", "real": "Damascus", "de": "Damaskus",
     "en": "Damascus", "ar": "دمشق", "note": "叙利亚地区中心；阿尤布王朝第二中心",
     "country_id": "C_SYRIA", "src": ["S1"]},
    {"id": "P_BAGHDAD", "type": "哈里发国都城", "zh": "巴格达", "real": "Baghdad", "de": "Bagdad",
     "en": "Baghdad", "ar": "بغداد", "note": "阿拔斯哈里发国首都",
     "country_id": "C_ABBASID", "src": ["S1"]},
    {"id": "P_ISFAHAN", "type": "沙阿都城", "zh": "伊斯法罕", "real": "Isfahan", "de": "Isfahan",
     "en": "Isfahan", "fa": "اصفهان", "note": "波斯后期首都",
     "country_id": "C_PERSIA", "src": ["S1"]},
    {"id": "P_MECCA", "type": "宗教圣地", "zh": "麦加", "real": "Mecca", "de": "Mekka",
     "en": "Mecca", "ar": "مكة", "note": "伊斯兰教第一圣地", "country_id": "C_ARABIA", "src": ["S1"]},
    {"id": "P_MEDINA", "type": "宗教圣地", "zh": "麦地那", "real": "Medina", "de": "Medina",
     "en": "Medina", "ar": "المدينة", "note": "伊斯兰教第二圣地", "country_id": "C_ARABIA", "src": ["S1"]},
    {"id": "P_GRANADA", "type": "城市", "zh": "格拉纳达", "real": "Granada", "de": "Granada",
     "en": "Granada", "es": "Granada", "ar": "غرناطة", "note": "安达卢斯最后据点",
     "country_id": "C_IBERIAN_KINGDOM", "src": ["S0"]},
    {"id": "P_BURSA", "type": "早期都城", "zh": "布尔萨", "real": "Bursa", "de": "Bursa",
     "en": "Bursa", "tr": "Bursa", "note": "安纳托利亚突厥帝国早期都城",
     "country_id": "C_ANATOLIAN_TURKS", "src": ["S1"]},
    {"id": "P_EDIRNE", "type": "早期都城", "zh": "埃迪尔内", "real": "Edirne", "de": "Edirne",
     "en": "Edirne", "tr": "Edirne", "note": "安纳托利亚突厥帝国早期都城",
     "country_id": "C_ANATOLIAN_TURKS", "src": ["S1"]},
    {"id": "P_TOULOUSE_OCC", "type": "王国中心（推定）", "zh": "图卢兹（奥克王国）",
     "real": "Toulouse", "de": "Tholosen", "en": "Toulouse", "fr": "Toulouse", "oc": "Tolosa",
     "note": "奥克王国的核心城市（推定）", "country_id": "C_OCCITAN_KINGDOM", "src": ["S0"]},
]

# 州名中的现实旧称说明（用于地理一致性报告）
GEO_NOTES = [
    {"topic": "法兰克州名用词", "finding": "S0 的州名清单中「卢瓦尔-奥尔良州」「加来-皮卡第州」「香槟-阿登州」「勃艮第-弗朗什孔泰州」等使用现实地名，而同表其他州用德语读音译名（弗兰登、诺德曼兰、弗兰肯岛、布里滕兰、利格-奥尔伦、罗登-阿尔卑斯）。",
     "handling": "州名作为设定集本文的固有名称保留原写法；但每一州的首府均按 S0 第四节「中文译名采用德语发音」的规则写作德语译名（奥尔良州→首府奥尔伦、加来-皮卡第州→首府卡莱斯、香槟-阿登州→首府雷姆斯、勃艮第-弗朗什孔泰州→首府迪根）。此不一致已记录，是否统一州名待用户裁定（待定项 P29）。",
     "status": "待定"},
]

# ============================================================
# 新增关系（伊比利亚线 / 伊斯兰世界线 / 新增人物家族）
# ============================================================
RELATIONS = [
    # ---------- 伊比利亚线的形成 ----------
    {"id": "REL401", "domain": "国家关系网", "kind": "SPLIT_FROM", "from": "C_IBERIAN_KINGDOM", "from_type": "COUNTRY", "to": "C_SPAIN_ARAGON", "to_type": "COUNTRY", "label": "伊比利亚王国由西班牙-阿拉贡（及奥克王国）逐步统一伊比利亚各基督教王国而成", "status": "已确定", "src": ["S2"]},
    {"id": "REL402", "domain": "国家关系网", "kind": "SPLIT_FROM", "from": "C_IBERIAN_KINGDOM", "from_type": "COUNTRY", "to": "C_OCCITAN_KINGDOM", "to_type": "COUNTRY", "label": "奥克王国为伊比利亚的前身之一（用户本轮补充）", "status": "已确定", "src": ["S2"]},
    {"id": "REL403", "domain": "国家关系网", "kind": "SUCCEEDED_BY", "from": "C_IBERIAN_KINGDOM", "from_type": "COUNTRY", "to": "C_IBERIA", "to_type": "COUNTRY", "label": "1789年伊比利亚-奥克大革命推翻伊比利亚王国，此后进入共和国/帝国反复更替（第一至第五共和国、第一至第二帝国）", "time": "1789", "status": "已确定", "src": ["S0", "S2"]},
    {"id": "REL404", "domain": "国家关系网", "kind": "ENEMY_OF", "from": "C_IBERIAN_KINGDOM", "from_type": "COUNTRY", "to": "C_CORDOBA", "to_type": "COUNTRY", "label": "收复失地运动：伊比利亚基督教诸王国逐出安达卢斯的穆斯林政权", "time": "8—15世纪", "status": "已确定", "src": ["S0", "S2"]},
    {"id": "REL405", "domain": "国家关系网", "kind": "ENEMY_OF", "from": "C_IBERIAN_KINGDOM", "from_type": "COUNTRY", "to": "C_ALMOHAD", "to_type": "COUNTRY", "label": "1212年穆瓦希德在伊比利亚战败，北非柏柏尔王朝的统治崩溃", "time": "1212", "status": "已确定", "src": ["S0", "S2"]},
    {"id": "REL406", "domain": "国家关系网", "kind": "TERRITORY_TRANSFER", "from": "C_ALMOHAD", "from_type": "COUNTRY", "to": "C_MAGHREB", "to_type": "COUNTRY", "label": "北非西部由柏柏尔王朝转归伊比利亚统治，此后长期基督教化、欧洲化", "time": "16世纪后", "status": "已确定", "src": ["S0", "S2"]},
    {"id": "REL407", "domain": "国家关系网", "kind": "SUZERAIN_OF", "from": "C_IBERIAN_KINGDOM", "from_type": "COUNTRY", "to": "C_MAGHREB", "to_type": "COUNTRY", "label": "伊比利亚南下北非驱逐穆斯林后长期统治马格里布；该地区无特殊宪制地位，与半岛同属一个国家行政体系", "status": "已确定", "src": ["S0", "S2"]},
    {"id": "REL408", "domain": "国家关系网", "kind": "BORDER_TENSION", "from": "C_IBERIA", "from_type": "COUNTRY", "to": "C_MAGHREB", "to_type": "COUNTRY", "label": "北非西部为伊比利亚本土一部分；撒哈拉承担文明分界功能（以北西部属欧洲、以东属亚洲）", "status": "已确定", "src": ["S2"]},
    {"id": "REL409", "domain": "国家关系网", "kind": "CULTURAL_HEGEMONY", "from": "C_OCCITAN_KINGDOM", "from_type": "COUNTRY", "to": "C_IBERIA", "to_type": "COUNTRY", "label": "奥克语与伊比利亚半岛语言共享词汇语法；奥克人认同“北伊比利亚人”或“奥克-伊比利亚人”", "status": "已确定", "src": ["S0"]},
    {"id": "REL410", "domain": "国家关系网", "kind": "BORDER_TENSION", "from": "C_OCCITAN_KINGDOM", "from_type": "COUNTRY", "to": "C_FRANKEN", "to_type": "COUNTRY", "label": "1648年维也纳和约：法兰克在奥克地区占领后撤，伊比利亚获得部分奥克领土；1789年大革命即爆发于此地", "time": "1648 / 1789", "status": "已确定", "src": ["S0"]},
    {"id": "REL411", "domain": "国家关系网", "kind": "SUZERAIN_OF", "from": "C_CORDOBA", "from_type": "COUNTRY", "to": "C_ALMOHAD", "to_type": "COUNTRY", "label": "科尔多瓦哈里发国1031年分裂后，北非穆拉比特与穆瓦希德两王朝先后渡海接管安达卢斯", "time": "11—13世纪", "status": "已确定", "src": ["S0", "S2"]},

    # ---------- 伊斯兰世界内部 ----------
    {"id": "REL420", "domain": "国家关系网", "kind": "RIVAL_OF", "from": "C_CORDOBA", "from_type": "COUNTRY", "to": "C_ABBASID", "to_type": "COUNTRY", "label": "929年科尔多瓦自立哈里发，伊斯兰世界形成三哈里发并立格局", "status": "已确定", "src": ["S0", "S1"]},
    {"id": "REL421", "domain": "国家关系网", "kind": "RIVAL_OF", "from": "C_FATIMID", "from_type": "COUNTRY", "to": "C_ABBASID", "to_type": "COUNTRY", "label": "什叶派法蒂玛哈里发国与逊尼派阿拔斯哈里发国对立", "status": "已确定", "src": ["S1"]},
    {"id": "REL422", "domain": "国家关系网", "kind": "SUCCEEDED_BY", "from": "C_FATIMID", "from_type": "COUNTRY", "to": "C_AYYUBID", "to_type": "COUNTRY", "label": "1171年萨拉丁推翻法蒂玛王朝，埃及转入逊尼派阿尤布王朝", "time": "1171", "status": "已确定", "src": ["S1"]},
    {"id": "REL423", "domain": "国家关系网", "kind": "SUCCEEDED_BY", "from": "C_AYYUBID", "from_type": "COUNTRY", "to": "C_MAMLUK", "to_type": "COUNTRY", "label": "1250年马穆鲁克取代阿尤布王朝", "time": "1250", "status": "已确定", "src": ["S1"]},
    {"id": "REL424", "domain": "国家关系网", "kind": "SUCCEEDED_BY", "from": "C_MAMLUK", "from_type": "COUNTRY", "to": "C_ANATOLIAN_TURKS", "to_type": "COUNTRY", "label": "1517年安纳托利亚突厥帝国吞并马穆鲁克统治的埃及与叙利亚，并取得汉志宗主权", "time": "1517", "status": "已确定", "src": ["S1"]},
    {"id": "REL425", "domain": "国家关系网", "kind": "ENEMY_OF", "from": "C_MAMLUK", "from_type": "COUNTRY", "to": "C_MONGOL_EMPIRE", "to_type": "COUNTRY", "label": "1260年马穆鲁克阻止蒙古西进，划出蒙古—金帐体系的西侧界线", "time": "1260", "status": "已确定", "src": ["S1", "S4"]},
    {"id": "REL426", "domain": "国家关系网", "kind": "RIVAL_OF", "from": "C_PERSIA", "from_type": "COUNTRY", "to": "C_ANATOLIAN_TURKS", "to_type": "COUNTRY", "label": "什叶派波斯与逊尼派安纳托利亚突厥帝国长期并立，构成伊斯兰世界的双极结构", "status": "已确定", "src": ["S1"]},
    {"id": "REL427", "domain": "国家关系网", "kind": "BORDER_TENSION", "from": "C_PERSIA", "from_type": "COUNTRY", "to": "C_WESTERN_REGIONS", "to_type": "COUNTRY", "label": "波斯的东界止于伊斯兰中亚西部；再往东即西域佛教带——这正是 S1 所定的“伊斯兰文明东部边界”", "status": "已确定", "src": ["S1"]},
    {"id": "REL428", "domain": "国家关系网", "kind": "TERRITORY_TRANSFER", "from": "C_ABBASID", "from_type": "COUNTRY", "to": "C_MONGOL_EMPIRE", "to_type": "COUNTRY", "label": "1258年巴格达陷落于蒙古西征军，阿拔斯哈里发国覆灭", "time": "1258", "status": "已确定", "src": ["S1"]},
    {"id": "REL429", "domain": "国家关系网", "kind": "RELIGIOUS_AFFILIATION", "from": "C_ARABIA", "from_type": "COUNTRY", "to": "R_ISLAM", "to_type": "RELIGION", "label": "麦加、麦地那两圣地所在，逊尼派为主", "status": "已确定", "src": ["S1"]},
    {"id": "REL430", "domain": "国家关系网", "kind": "SUZERAIN_OF", "from": "C_ANATOLIAN_TURKS", "from_type": "COUNTRY", "to": "C_ARABIA", "to_type": "COUNTRY", "label": "1517年后取得汉志两圣地的宗主权", "time": "1517后", "status": "已确定", "src": ["S1"]},
    {"id": "REL431", "domain": "国家关系网", "kind": "SUZERAIN_OF", "from": "C_FATIMID", "from_type": "COUNTRY", "to": "C_ARABIA", "to_type": "COUNTRY", "label": "法蒂玛王朝势力及于汉志", "time": "10—12世纪", "status": "已确定", "src": ["S1"]},
    {"id": "REL432", "domain": "国家关系网", "kind": "SUZERAIN_OF", "from": "C_AYYUBID", "from_type": "COUNTRY", "to": "C_SYRIA", "to_type": "COUNTRY", "label": "阿尤布王朝统合埃及与叙利亚", "status": "已确定", "src": ["S1"]},
    {"id": "REL433", "domain": "国家关系网", "kind": "SUZERAIN_OF", "from": "C_MAMLUK", "from_type": "COUNTRY", "to": "C_SYRIA", "to_type": "COUNTRY", "label": "马穆鲁克统治叙利亚", "status": "已确定", "src": ["S1"]},
    {"id": "REL434", "domain": "国家关系网", "kind": "SUZERAIN_OF", "from": "C_ANATOLIAN_TURKS", "from_type": "COUNTRY", "to": "C_SYRIA", "to_type": "COUNTRY", "label": "1517年后叙利亚并入安纳托利亚突厥帝国", "time": "1517后", "status": "已确定", "src": ["S1"]},
    {"id": "REL435", "domain": "国家关系网", "kind": "BORDER_TENSION", "from": "C_ANATOLIAN_TURKS", "from_type": "COUNTRY", "to": "C_BYZANTIUM", "to_type": "COUNTRY", "label": "安纳托利亚突厥帝国与基督教君士坦丁堡/海峡政治体长期对峙共处；“海峡是文明边界，而不是文明墙”", "status": "已确定", "src": ["S1"]},
    {"id": "REL436", "domain": "国家关系网", "kind": "RELIGIOUS_AFFILIATION", "from": "C_EGYPT_REGION", "from_type": "COUNTRY", "to": "R_ISLAM", "to_type": "RELIGION", "label": "逊尼派伊斯兰为主；科普特教会长期存续", "status": "已确定", "src": ["S2"]},
    {"id": "REL437", "domain": "国家关系网", "kind": "RELIGIOUS_AFFILIATION", "from": "C_ISLAMIC_WORLD", "from_type": "COUNTRY", "to": "R_ISLAM", "to_type": "RELIGION", "label": "伊斯兰世界为区域文明体集合，无单一最高政治权威", "status": "已确定", "src": ["S1"]},

    # ---------- 法兰克与近东 ----------
    {"id": "REL440", "domain": "国家关系网", "kind": "ENEMY_OF", "from": "C_FRANKEN", "from_type": "COUNTRY", "to": "C_AYYUBID", "to_type": "COUNTRY", "label": "十字军东征：法兰西罗曼王国—教皇国一方对抗黎凡特穆斯林政权", "time": "11—13世纪", "status": "已确定", "src": ["S1"]},
    {"id": "REL441", "domain": "国家关系网", "kind": "ENEMY_OF", "from": "C_FRANKEN", "from_type": "COUNTRY", "to": "C_FATIMID", "to_type": "COUNTRY", "label": "十字军东征：法兰克—教皇国一方对抗黎凡特穆斯林政权", "time": "11—13世纪", "status": "已确定", "src": ["S1"]},
    {"id": "REL442", "domain": "国家关系网", "kind": "ENEMY_OF", "from": "C_FRANKEN", "from_type": "COUNTRY", "to": "C_MAMLUK", "to_type": "COUNTRY", "label": "1291年马穆鲁克夺取黎凡特沿岸最后据点，法兰西罗曼王国在大陆东岸的军事存在终结", "time": "至1291", "status": "已确定", "src": ["S1"]},
    {"id": "REL443", "domain": "国家关系网", "kind": "TRADE_PARTNER", "from": "C_FRANKEN", "from_type": "COUNTRY", "to": "C_SYRIA", "to_type": "COUNTRY", "label": "法兰克以商业、传教与学术方式维持近东联系，形成帕里斯东方学传统", "status": "已确定", "src": ["S1"]},
    {"id": "REL444", "domain": "国家关系网", "kind": "CULTURAL_HEGEMONY", "from": "C_FRANKEN", "from_type": "COUNTRY", "to": "C_MAGHREB", "to_type": "COUNTRY", "label": "法兰克承继法兰西罗曼王国的北非、黎凡特传统影响；帕里斯有神学、历史、东方学传统", "status": "已确定", "src": ["S1"]},
    {"id": "REL445", "domain": "国家关系网", "kind": "ALLY_OF", "from": "C_PAPAL", "from_type": "COUNTRY", "to": "C_FRANKEN", "to_type": "COUNTRY", "label": "十字军东征中教皇国与法兰克同阵营", "time": "11—13世纪", "status": "已确定", "src": ["S1"]},

    # ---------- 伊斯兰世界线的补充对位（与既有实体） ----------
    {"id": "REL450", "domain": "国家关系网", "kind": "ENEMY_OF", "from": "C_ANATOLIAN_TURKS", "from_type": "COUNTRY", "to": "C_ROS_UHLUS", "to_type": "COUNTRY", "label": "安纳托利亚突厥帝国与罗斯兀鲁思在黑海—高加索方向长期对峙（S2 将二者同划入亚洲）", "status": "待定", "src": ["S2", "S4"]},
    {"id": "REL451", "domain": "国家关系网", "kind": "CULTURAL_HEGEMONY", "from": "C_ISLAMIC_WORLD", "from_type": "COUNTRY", "to": "C_ASIA_CONTINENT", "to_type": "COUNTRY", "label": "S2 的亚洲文明大洲以“俄罗斯—西亚—伊斯兰文明空间”为核心构成", "status": "已确定", "src": ["S2"]},
    {"id": "REL452", "domain": "国家关系网", "kind": "RELIGIOUS_AFFILIATION", "from": "C_MAGHREB", "from_type": "COUNTRY", "to": "R_CATHOLIC", "to_type": "RELIGION", "label": "北非西部经伊比利亚长期统治后基督教化", "status": "已确定", "src": ["S0", "S2"]},

    # ---------- 人物家族网补全 ----------
    {"id": "REL460", "domain": "人物家族网", "kind": "PARENT_OF", "from": "PE_PHILIP_III", "from_type": "PERSON", "to": "PE_CAPET_SONS", "to_type": "PERSON", "label": "父子（查理、路易，文档未具名者合并）", "status": "已确定", "src": ["S0"]},
    {"id": "REL461", "domain": "人物家族网", "kind": "SPOUSE_OF", "from": "PE_PHILIP_III", "from_type": "PERSON", "to": "PE_PHILIP_III_WIFE", "to_type": "PERSON", "label": "夫妻（文档未具名）", "status": "已确定", "src": ["S0"]},
    {"id": "REL462", "domain": "人物家族网", "kind": "PARENT_OF", "from": "PE_BURGUNDY_COUNT", "from_type": "PERSON", "to": "PE_RUDOLF_WIFE", "to_type": "PERSON", "label": "父女（文档未具名）", "status": "已确定", "src": ["S0", "S1"]},
    {"id": "REL463", "domain": "人物家族网", "kind": "SPOUSE_OF", "from": "PE_ALBRECHT_II_SON_IN_LAW", "from_type": "PERSON", "to": "PE_ALBRECHT_II_DAUGHTER", "to_type": "PERSON", "label": "夫妻（文档未具名）", "status": "已确定", "src": ["S0"]},
    {"id": "REL464", "domain": "人物家族网", "kind": "CLAIMANT_TO", "from": "PE_BRITTANY_DUKE", "from_type": "PERSON", "to": "C_FRANKEN", "to_type": "COUNTRY", "label": "法兰克王位继承争夺者（1270年前后，失败）", "status": "已确定", "src": ["S0"]},
    {"id": "REL465", "domain": "人物家族网", "kind": "RIVAL_OF", "from": "PE_NORMANDY_DUKE", "from_type": "PERSON", "to": "PE_RUDOLF", "to_type": "PERSON", "label": "1272年决战：诺曼底公爵败于鲁道夫", "status": "已确定", "src": ["S0", "S1"]},
    {"id": "REL466", "domain": "人物家族网", "kind": "OFFICE_HOLD", "from": "PE_REIMS_ARCHBISHOP", "from_type": "PERSON", "to": "PE_RUDOLF", "to_type": "PERSON", "label": "1272年为鲁道夫加冕为“法兰克人的国王”", "status": "已确定", "src": ["S0", "S1"]},
    {"id": "REL467", "domain": "人物家族网", "kind": "DYNASTY_MEMBER", "from": "PE_ABD_AL_RAHMAN_III", "from_type": "PERSON", "to": "D_UMAYYAD", "to_type": "DYNASTY", "label": "伍麦叶西班牙支系", "status": "已确定", "src": ["S0"]},
    {"id": "REL468", "domain": "人物家族网", "kind": "DYNASTY_MEMBER", "from": "PE_SALADIN", "from_type": "PERSON", "to": "D_AYYUBID", "to_type": "DYNASTY", "label": "阿尤布王朝创立者", "status": "已确定", "src": ["S1"]},
    {"id": "REL469", "domain": "人物家族网", "kind": "DYNASTY_MEMBER", "from": "PE_BAIBARS", "from_type": "PERSON", "to": "D_MAMLUK", "to_type": "DYNASTY", "label": "马穆鲁克苏丹", "status": "已确定", "src": ["S1"]},
    {"id": "REL470", "domain": "人物家族网", "kind": "DYNASTY_MEMBER", "from": "PE_SCHAH_ISMAIL", "from_type": "PERSON", "to": "D_PERSIAN_LINE", "to_type": "DYNASTY", "label": "波斯什叶派国家传统的奠基者（推定）", "status": "待定", "src": ["S1"]},
    {"id": "REL471", "domain": "人物家族网", "kind": "DYNASTY_MEMBER", "from": "PE_OSMAN_I", "from_type": "PERSON", "to": "D_OTTOMAN", "to_type": "DYNASTY", "label": "安纳托利亚突厥王朝奠基者", "status": "待定", "src": ["S1"]},
    {"id": "REL472", "domain": "人物家族网", "kind": "DYNASTY_MEMBER", "from": "PE_IBERIA_KING_FOUNDER", "from_type": "PERSON", "to": "D_IBERIA_DYNASTY", "to_type": "DYNASTY", "label": "伊比利亚王国开国君主（占位，姓名待定）", "status": "待定", "src": ["S2"]},
    {"id": "REL473", "domain": "人物家族网", "kind": "SUBJECT_OF", "from": "PE_JOHANNA_VON_ARKON", "from_type": "PERSON", "to": "C_FRANKEN", "to_type": "COUNTRY", "label": "法兰克抗伊比利亚民兵领袖（推定）", "status": "待定", "src": ["S0"]},
    {"id": "REL474", "domain": "人物家族网", "kind": "SUBJECT_OF", "from": "PE_KARDINAL_RICHELIEU", "from_type": "PERSON", "to": "C_FRANKEN", "to_type": "COUNTRY", "label": "法兰克帝国首相（推定）", "status": "待定", "src": ["S0", "S1"]},

    # ---------- 新增事件因果 ----------
    {"id": "REL480", "domain": "事件因果链", "kind": "CAUSES", "from": "E_0929_CORDOBA", "from_type": "EVENT", "to": "E_1031_TAIFAS", "to_type": "EVENT", "label": "哈里发国的集权并未持久，1031年分裂", "status": "已确定", "src": ["S0"]},
    {"id": "REL481", "domain": "事件因果链", "kind": "RESULTS_IN", "from": "E_1031_TAIFAS", "from_type": "EVENT", "to": "E_1212_LAS_NAVAS", "to_type": "EVENT", "label": "安达卢斯碎片化后由北非柏柏尔王朝接管，最终1212年战败", "status": "已确定", "src": ["S0", "S2"]},
    {"id": "REL482", "domain": "事件因果链", "kind": "CAUSES", "from": "E_1212_LAS_NAVAS", "from_type": "EVENT", "to": "E_RECONQUISTA", "to_type": "EVENT", "label": "穆瓦希德战败是收复失地运动的转折点", "status": "已确定", "src": ["S0", "S2"]},
    {"id": "REL483", "domain": "事件因果链", "kind": "RESULTS_IN", "from": "E_RECONQUISTA", "from_type": "EVENT", "to": "E_IBERIAN_UNIFICATION", "to_type": "EVENT", "label": "收复失地运动形成共同基督教/伊比利亚身份，进而导向统一", "status": "已确定", "src": ["S2"]},
    {"id": "REL484", "domain": "事件因果链", "kind": "RESULTS_IN", "from": "E_IBERIAN_UNIFICATION", "from_type": "EVENT", "to": "E_MAGHREB_CHRISTIANISATION", "to_type": "EVENT", "label": "统一后的伊比利亚南下北非驱逐穆斯林", "status": "已确定", "src": ["S0", "S2"]},
    {"id": "REL485", "domain": "事件因果链", "kind": "CAUSES", "from": "E_IBERIAN_UNIFICATION", "from_type": "EVENT", "to": "E_1789_REVOLUTION", "to_type": "EVENT", "label": "伊比利亚王国的中央集权在1789年被大革命推翻", "status": "已确定", "src": ["S0", "S2"]},
    {"id": "REL486", "domain": "事件因果链", "kind": "CAUSES", "from": "E_CRUSADES", "from_type": "EVENT", "to": "E_1291_ACRE", "to_type": "EVENT", "label": "十字军在地中海东岸的军事存在最终终结", "status": "已确定", "src": ["S1"]},
    {"id": "REL487", "domain": "事件因果链", "kind": "RESULTS_IN", "from": "E_1291_ACRE", "from_type": "EVENT", "to": "E_FRANKISH_ORIENTALISM", "to_type": "EVENT", "label": "法兰克转为以商业、传教与学术维持近东联系，形成东方学传统", "status": "已确定", "src": ["S1"]},
    {"id": "REL488", "domain": "事件因果链", "kind": "CAUSES", "from": "E_1200_MONGOL", "from_type": "EVENT", "to": "E_MAMLUK_MONGOL", "to_type": "EVENT", "label": "蒙古西征引发马穆鲁克的阻击", "status": "已确定", "src": ["S1", "S4"]},
    {"id": "REL489", "domain": "事件因果链", "kind": "CAUSES", "from": "E_MAMLUK_MONGOL", "from_type": "EVENT", "to": "E_1517_MAMLUK_END", "to_type": "EVENT", "label": "马穆鲁克长期维持独立，最终为安纳托利亚突厥帝国取代", "status": "已确定", "src": ["S1"]},
    {"id": "REL490", "domain": "事件因果链", "kind": "CAUSES", "from": "E_1517_MAMLUK_END", "from_type": "EVENT", "to": "E_1501_PERSIA_SHIITE", "to_type": "EVENT", "label": "近东整合为逊尼派帝国，与波斯什叶派体系形成双极并立", "status": "已确定", "src": ["S1"]},
    {"id": "REL491", "domain": "事件因果链", "kind": "PARTICIPATES_IN", "from": "PE_ALFONS_X", "from_type": "PERSON", "to": "E_RECONQUISTA", "to_type": "EVENT", "label": "卡斯蒂利亚扩张的推动者", "status": "已确定", "src": ["S2"]},
    {"id": "REL492", "domain": "事件因果链", "kind": "PARTICIPATES_IN", "from": "PE_ISABELLA_VON_KASTILIEN", "from_type": "PERSON", "to": "E_IBERIAN_UNIFICATION", "to_type": "EVENT", "label": "伊比利亚统一的推动者（推定）", "status": "待定", "src": ["S2"]},
    {"id": "REL493", "domain": "事件因果链", "kind": "PARTICIPATES_IN", "from": "PE_SALADIN", "from_type": "PERSON", "to": "E_CRUSADES", "to_type": "EVENT", "label": "1187年收复耶路撒冷", "status": "已确定", "src": ["S1"]},
    {"id": "REL494", "domain": "事件因果链", "kind": "PARTICIPATES_IN", "from": "PE_BAIBARS", "from_type": "PERSON", "to": "E_MAMLUK_MONGOL", "to_type": "EVENT", "label": "1260年击败蒙古西征军", "status": "已确定", "src": ["S1", "S4"]},
    {"id": "REL495", "domain": "事件因果链", "kind": "PARTICIPATES_IN", "from": "PE_SCHAH_ISMAIL", "from_type": "PERSON", "to": "E_1501_PERSIA_SHIITE", "to_type": "EVENT", "label": "确立什叶派为国教（推定）", "status": "待定", "src": ["S1"]},
    {"id": "REL496", "domain": "事件因果链", "kind": "PARTICIPATES_IN", "from": "PE_OSMAN_I", "from_type": "PERSON", "to": "E_1517_MAMLUK_END", "to_type": "EVENT", "label": "其奠基的王朝最终取代马穆鲁克", "status": "已确定", "src": ["S1"]},
    {"id": "REL497", "domain": "事件因果链", "kind": "PARTICIPATES_IN", "from": "PE_JOHANNA_VON_ARKON", "from_type": "PERSON", "to": "E_RECONQUISTA", "to_type": "EVENT", "label": "法兰克方向对伊比利亚压力的抵抗（推定）", "status": "待定", "src": ["S0"]},
]

